---
name: node-red
services:
  node-red:
    image: nodered/node-red:5.0.6
    container_name: node-red
    volumes:
      - ./data:/data
      - ./settings.js:/data/settings.js:ro
      - ./flows.json:/data/flows.json
    environment:
      - TZ="America/Chicago"
    env_file:
      - .env
    networks:
      - proxy
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.node-red.entrypoints=websecure
      - traefik.http.routers.node-red.rule=Host(`hook.jstockley.com`)
      - traefik.http.routers.node-red.tls=true
      - traefik.http.routers.node-red.tls.certresolver=production
      - traefik.http.routers.node-red.service=node-red
      - traefik.http.services.node-red.loadbalancer.server.port=1880
      - traefik.docker.network=proxy

networks:
  proxy:
    name: proxy
    external: true
    enable_ipv4: true
    enable_ipv6: true
