---
tcp:
  routers:
    adguard-dot:
      rule: "HostSNI(`*.dns.local.jstockley.com`) || HostSNI(`*.dns.jstockley.com`)"
      entryPoints:
        - "dot"
      service: adguard-dot
      tls:
        certResolver: "production"
        domains:
          - main: "*.dns.jstockley.com"
            sans:
              - "*.dns.local.jstockley.com"

  services:
    adguard-dot:
      loadBalancer:
        servers:
          - address: "adguard:53"
