---
http:
  services:
    authentik-outpost:
      loadBalancer:
        servers:
          - url: "http://authentik:9000"
        passHostHeader: true

  middlewares:
    authentik-proxy-secure-headers:
      headers:
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 63072000                        # 2 years
        customFrameOptionsValue: SAMEORIGIN
        referrerPolicy: "strict-origin-when-cross-origin"
        permissionsPolicy: "camera=(), microphone=(), geolocation=()"
        customResponseHeaders:
          X-Robots-Tag: "noindex, nofollow, nosnippet, noarchive"

    authentik-rate-limit:
      rateLimit:
        average: 100
        burst: 50

    authentik-proxy-chain:
      chain:
        middlewares:
          - authentik-proxy-secure-headers
          - authentik-rate-limit
