---
http:
  routers:
    cockpit:
      rule: "Host(`cockpit.local.jstockley.com`)"
      entryPoints:
        - websecure
      service: cockpit
      tls:
        certResolver: production
  services:
    cockpit:
      loadBalancer:
        servers:
          - url: "https://localhost:9090"
