---
http:
  routers:
    cockpit:
      rule: "Host(`cockpit.local.jstockley.com`)"
      entryPoints:
        - websecure
      service: cockpit
      tls:
        certResolver: production
  services:
    cockpit:
      loadBalancer:
        passHostHeader: true
        serversTransport: cockpit-transport
        servers:
          - url: "https://host.docker.internal:9090"

  serversTransports:
    cockpit-transport:
      insecureSkipVerify: true
