---
http:
  routers:
    homeassistant:
      rule: "Host(`home.jstockley.com`)"
      entryPoints:
        - websecure
      service: homeassistant
      tls:
        certResolver: production
  services:
    homeassistant:
      loadBalancer:
        servers:
          - url: "http://192.168.1.119:8123"
