---
http:
  routers:
    homeassistant:
      rule: "Host(`iowa-home.jstockley.com`)"
      entryPoints:
        - websecure
      service: homeassistant
      tls:
        certResolver: production
  services:
    homeassistant:
      loadBalancer:
        servers:
          - url: "http://192.168.0.107:8123"
