---
http:
  routers:
    proxmox:
      rule: "Host(`proxmox.local.jstockley.com`)"
      entryPoints:
        - websecure
      service: proxmox
      tls:
        certResolver: production
  services:
    proxmox:
      loadBalancer:
        servers:
          - url: "https://192.168.1.18:8006"
