---
http:
  routers:
    homeassistant:
      rule: "Host(`unifi.local.jstockley.com`)"
      entryPoints:
        - websecure
      service: homeassistant
      tls:
        certResolver: production
  services:
    homeassistant:
      loadBalancer:
        servers:
          - url: "https://192.168.1.142:8443"
