---
http:
  routers:
    unifi:
      rule: "Host(`unifi.local.jstockley.com`)"
      entryPoints:
        - websecure
      service: unifi
      tls:
        certResolver: production
  services:
    unifi:
      loadBalancer:
        servers:
          - url: "https://192.168.1.141:8443"
