services:
  adguard:
    container_name: adguard
    image: adguard/adguardhome:v0.107.48
    networks:
      adguard:
        ipv4_address: 172.18.0.3
    restart: unless-stopped
    volumes:
      - ./conf:/opt/adguardhome/conf
      - ./work:/opt/adguardhome/work
    environment:
      - TZ=America/Chicago
    ports:
      - 53:53
    cap_add:
      - NET_ADMIN
    labels:
      - traefik.enable=true
      - traefik.http.routers.adguard.entrypoints=web
      - traefik.http.routers.adguard.rule=Host(`dns.jstockley.com`)
      - traefik.http.middlewares.adguard-https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.adguard.middlewares=adguard-https-redirect
      - traefik.http.routers.adguard-secure.entrypoints=websecure
      - traefik.http.routers.adguard-secure.rule=Host(`dns.jstockley.com`)
      - traefik.http.routers.adguard-secure.tls=true
      - traefik.http.routers.adguard-secure.tls.certresolver=production
      - traefik.http.routers.adguard-secure.service=adguard
      - traefik.http.services.adguard.loadbalancer.server.port=80
      - traefik.docker.network=adguard
    healthcheck:
      test: wget --no-verbose --tries=1 --spider --no-check-certificate https://localhost
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

networks:
  adguard:
    external: true
    name: adguard
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24