---
name: gitea
services:
  server:
    image: gitea/gitea:1.26.1
    container_name: gitea
    volumes:
      - ./data:/data
    environment:
      - TZ=America/Chicago
      - GITEA__service__DISABLE_REGISTRATION=true
      - GITEA__openid__ENABLE_OPENID_SIGNIN=true
      - GITEA__openid__ENABLE_OPENID_SIGNUP=false
    env_file:
      - ./.env
    networks:
      - proxy
      - private
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:3000/api/healthz || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 100s
    labels:
      - traefik.enable=true
      - traefik.http.routers.gitea.entrypoints=websecure
      - traefik.http.routers.gitea.rule=Host(`git.jstockley.com`)
      - traefik.http.routers.gitea.tls=true
      - traefik.http.routers.gitea.tls.certresolver=production
      - traefik.http.routers.gitea.service=gitea
      - traefik.http.services.gitea.loadbalancer.server.port=3000
      - traefik.docker.network=proxy
    security_opt:
      - no-new-privileges:true

networks:
  proxy:
    name: proxy
    external: true
    enable_ipv4: true
    enable_ipv6: true
  private:
    name: private
    internal: true
    external: true
    enable_ipv4: true
    enable_ipv6: true
