---
name: gitea
services:
  server:
    image: gitea/gitea:1.22.6
    container_name: gitea
    volumes:
      - ./data:/data
    environment:
      - TZ=America/Chicago
    env_file:
      - ./.env
    networks:
      - gitea
      - postgres
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:3000/api/healthz || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 100s
    labels:
      - traefik.enable=true
      - traefik.http.routers.gitea.entrypoints=websecure
      - traefik.http.routers.gitea.rule=Host(`git.jstockley.com`)
      - traefik.http.routers.gitea.tls=true
      - traefik.http.routers.gitea.tls.certresolver=production
      - traefik.http.routers.gitea.service=gitea
      - traefik.http.services.gitea.loadbalancer.server.port=3000
      - traefik.docker.network=gitea
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true

networks:
  gitea:
    name: gitea
    external: true
  postgres:
    name: postgres
    external: true
