services:
  server:
    image: gitea/gitea:1.22.3
    container_name: gitea
    restart: always
    env_file:
      - ./.env
    environment:
      - TZ=America/Chicago
    volumes:
      - ./data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - gitea
      - postgres-internal
    labels:
      - traefik.enable=true
      - traefik.http.routers.gitea.entrypoints=websecure
      - traefik.http.routers.gitea.rule=Host(`git.jstockley.com`)
      - traefik.http.routers.gitea.tls=true
      - traefik.http.routers.gitea.tls.certresolver=production
      - traefik.http.routers.gitea.service=gitea
      - traefik.http.services.gitea.loadbalancer.server.port=3000
      - traefik.docker.network=gitea

networks:
  gitea:
    external: true
    name: gitea
  postgres-internal:
    external: true
    name: postgres-internal
