---
name: syncthing
services:
  syncthing:
    image: syncthing/syncthing:1.29.0
    container_name: syncthing
    volumes:
      - ./config:/var/syncthing/config
      - /mnt/photos/:/var/syncthing/photos
      - /home/jackstockley/infrastructure/docker/photo-server:/var/syncthing/docker
    environment:
      - TZ=America/Chicago
      - PUID=0
      - PGID=0
    ports:
      - '0.0.0.0:8384:8384'
    networks:
      - syncthing
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:8384/rest/noauth/health || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 100s
    labels:
      - traefik.enable=true
      - traefik.http.routers.backup.entrypoints=websecure
      - traefik.http.routers.backup.rule=Host(`backup.local.jstockley.com`)
      - traefik.http.routers.backup.tls=true
      - traefik.http.routers.backup.tls.certresolver=production
      - traefik.http.routers.backup.service=backup
      - traefik.http.services.backup.loadbalancer.server.port=8384
      - traefik.docker.network=syncthing
    deploy:
      resources:
        limits:
          memory: 512M
    hostname: syncthing_photo_server
    security_opt:
      - no-new-privileges:true

networks:
  syncthing:
    name: syncthing
    external: true
