services:
  renovate-ce:
    # Check latest version here: https://github.com/mend/renovate-ce-ee/pkgs/container/renovate-ce
    image: ghcr.io/mend/renovate-ce:8.4.0-full
    labels:
      - traefik.enable=true
      - traefik.http.routers.mend.entrypoints=websecure
      - traefik.http.routers.mend.rule=Host(`mend.jstockley.com`)
      - traefik.http.routers.mend.tls=true
      - traefik.http.routers.mend.tls.certresolver=production
      - traefik.http.routers.mend.service=mend
      - traefik.http.services.mend.loadbalancer.server.port=8080
      - traefik.docker.network=mend
    volumes:
      - ./logs:/logs
      - certs:/usr/src/app/
    environment:
      # Optional: Enable debug logging for verbose output
      LOG_LEVEL: debug  # Defaults to 'info'
      # LOG_FORMAT: json  # Defaults to 'pretty'. Useful when importing logs to reporting tool (eg. Splunk).

      # Provide a license key and accept the Terms of Service
      MEND_RNV_LICENSE_KEY: # Get Community Edition license key from https://www.mend.io/renovate-community/
      MEND_RNV_ACCEPT_TOS: # Set to 'Y' to accept Terms of Service
      # Provide connection details for the GitHub App
      # Available at: https://github.com/settings/apps/<your-renovate-app>
      MEND_RNV_PLATFORM: github
      MEND_RNV_GITHUB_APP_ID: # App ID
      MEND_RNV_GITHUB_APP_KEY: # Private key
      # MEND_RNV_WEBHOOK_SECRET: # Webhook secret (Defaults to 'renovate')

      # Mend Renovate Application settings (Optional)
      # MEND_RNV_ADMIN_API_ENABLED: true  # Enable incoming API calls. Must set MEND_RNV_SERVER_API_SECRET.
      # MEND_RNV_SERVER_API_SECRET: abc123 # Required to enable APIs
      # MEND_RNV_LOG_HISTORY_DIR: /logs  # Persist Renovate job logs - organized by org/rep/timestamp. Enable volume mount!
      # MEND_RNV_ENQUEUE_JOBS_ON_STARTUP: disabled  # Options: 'enabled', 'disabled', 'discovered' (default)
      # MEND_RNV_AUTODISCOVER_FILTER: org1/*, org2/test* # Renovate will only run on these repos

      # Connection details to the Postgres DB
      MEND_RNV_DATA_HANDLER_TYPE: postgresql
      PGDATABASE: postgres
      PGUSER: postgres
      PGPASSWORD: password
      PGHOST: postgres-database
      PGPORT: 5432
