---
name: tailscale
services:
  tailscale:
    image: tailscale/tailscale:v1.84.0
    container_name: tailscale
    volumes:
      - /dev/net/tun:/dev/net/tun
      - ./data:/var/lib/tailscale
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_EXTRA_ARGS=--advertise-exit-node --advertise-tags=tag:container
        --advertise-routes=172.0.0.0/8
      - TZ=America/Chicago
      # - TS_USERSPACE=false
    env_file:
      - .env
    networks:
      - tailscale
      - syncthing
      - uptime-kuma
      - adguard
      - vaultwarden
      - postgres
    restart: unless-stopped
    healthcheck:
      test: ping -c "3" racknerd
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    deploy:
      resources:
        limits:
          memory: 128M
    hostname: racknerd
    security_opt:
      - no-new-privileges:true

networks:
  tailscale:
    name: tailscale
    external: true
  syncthing:
    name: syncthing
    external: true
  uptime-kuma:
    name: uptime-kuma
    external: true
  adguard:
    name: adguard
    external: true
  vaultwarden:
    name: vaultwarden
    external: true
  postgres:
    name: postgres
    external: true
