services:
  tailscale:
    image: tailscale/tailscale:v1.64.2
    container_name: tailscale
    hostname: racknerd
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_EXTRA_ARGS=--advertise-exit-node --advertise-tags=tag:container --advertise-routes=172.0.0.0/8
      - TZ=America/Chicago
    env_file:
      - ./.env
    volumes:
      - /dev/net/tun:/dev/net/tun
      - ./data:/var/lib/tailscale
    networks:
      tailscale:
      syncthing:
        ipv4_address: 172.18.8.3
      uptime-kuma:
      adguard:
        ipv4_address: 172.18.0.3
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
    healthcheck:
      test:
        - CMD
        - ping
        - -c
        - "3"
        - racknerd
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

networks:
  tailscale:
    external: true
    name: tailscale
    ipam:
      driver: default
      config:
        - subnet: 172.19.3.0/24
  syncthing:
    external: true
    name: syncthing
    ipam:
      driver: default
      config:
        - subnet: 172.18.8.0/24
  uptime-kuma:
    external: true
    name: uptime-kuma
    ipam:
      driver: default
      config:
        - subnet: 172.18.4.0/24
  adguard:
    external: true
    name: adguard
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24
