services:
  tailscale:
    image: tailscale/tailscale:v1.62.1
    container_name: tailscale
    hostname: racknerd
    environment:
      - TS_EXTRA_ARGS=-advertise-exit-node
      - TZ=America/Chicago
    env_file:
      - path: ./.env
        required: true
    volumes:
      - /dev/net/tun:/dev/net/tun
    networks:
      - tailscale
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped

networks:
  tailscale:
    external: true
    name: "tailscale"