services:
  tailscale:
    image: tailscale/tailscale:v1.64.2
    container_name: tailscale
    hostname: racknerd
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_EXTRA_ARGS=--advertise-exit-node --advertise-tags=tag:container --advertise-routes=172.0.0.0/8
      - TZ=America/Chicago
    env_file:
      - ./.env
    volumes:
      - /dev/net/tun:/dev/net/tun
      - ./data:/var/lib/tailscale
    networks:
      - tailscale
      - syncthing
      - uptime-kuma
      - adguard
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
    healthcheck:
      test:
        - CMD
        - ping
        - -c
        - "3"
        - racknerd
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

networks:
  tailscale:
    external: true
    name: tailscale
  syncthing:
    external: true
    name: syncthing
  uptime-kuma:
    external: true
    name: uptime-kuma
  adguard:
    external: true
    name: adguard
