services:
  tailscale:
    image: tailscale/tailscale:v1.62.1
    container_name: tailscale
    hostname: racknerd
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_EXTRA_ARGS=--advertise-exit-node --advertise-tags=tag:container --accept-routes=172.0.0.0/8
      - TZ=America/Chicago
    env_file:
      - path: ./.env
        required: true
    volumes:
      - /dev/net/tun:/dev/net/tun
      - ./data:/var/lib/tailscale
    networks:
      - tailscale
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped

networks:
  tailscale:
    external: true
    name: "tailscale"