---
name: grafana
services:
  grafana:
    image: docker.io/grafana/grafana-oss:11.6.1
    container_name: grafana
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - proxy
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.services.grafana.loadbalancer.server.port=3000
      - traefik.http.routers.grafana.entrypoints=websecure
      - traefik.http.routers.grafana.rule=Host(`grafana.local.jstockley.com`)
      - traefik.http.routers.grafana.tls=true
      - traefik.http.routers.grafana.tls.certresolver=production
      - traefik.http.routers.grafana.service=grafana
    security_opt:
      - no-new-privileges:true

networks:
  proxy:
    name: proxy
    external: true

volumes:
  grafana-data:
    driver: local
