---
services:
  loki:
    image: grafana/loki:3.3.0
    volumes:
      - ./loki:/etc/loki
    #ports:
    #  - "3100:3100"
    labels:
      - traefik.enable=true
      - traefik.http.routers.loki.entrypoints=websecure
      - traefik.http.routers.loki.rule=Host(`log.jstockley.com`)
      - traefik.http.routers.loki.tls=true
      - traefik.http.routers.loki.tls.certresolver=production
      - traefik.http.routers.loki.service=loki
      - traefik.http.services.loki.loadbalancer.server.port=3100
      - traefik.docker.network=loki
    restart: unless-stopped
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - loki
  promtail:
    image: grafana/promtail:3.3.0
    volumes:
      - /var/log:/var/log
      - ./promtail:/etc/promtail
    # ports:
    #   - "1514:1514" # this is only needed if you are going to send syslogs
    restart: unless-stopped
    command: -config.file=/etc/promtail/promtail-config.yml
    networks:
      - loki
  grafana:
    image: grafana/grafana:11.3.1
    user: "1000"
    volumes:
    - ./grafana:/var/lib/grafana
    #ports:
    #  - "3000:3000"
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.entrypoints=websecure
      - traefik.http.routers.grafana.rule=Host(`log.jstockley.com`)
      - traefik.http.routers.grafana.tls=true
      - traefik.http.routers.grafana.tls.certresolver=production
      - traefik.http.routers.grafana.service=grafana
      - traefik.http.services.grafana.loadbalancer.server.port=3000
      - traefik.docker.network=loki
    restart: unless-stopped
    networks:
      - loki

networks:
  loki:
    name: loki
    external: true
