---
name: syncthing
services:
  syncthing:
    image: syncthing/syncthing:2.1.1
    container_name: syncthing
    volumes:
      - ./config:/var/syncthing/config
      - /mnt/backup/:/var/syncthing/nextcloud
      - /home/jackstockley/infrastructure/docker/racknerd/:/var/syncthing/docker
    environment:
      - TZ=America/Chicago
      - PUID=0
      - PGID=0
    networks:
      - proxy
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:8384/rest/noauth/health || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 100s
    labels:
      - traefik.enable=true
      - traefik.http.routers.syncthing.entrypoints=websecure
      - traefik.http.routers.syncthing.rule=Host(`backup.jstockley.com`)
      - traefik.http.routers.syncthing.tls=true
      - traefik.http.routers.syncthing.tls.certresolver=production
      - traefik.http.routers.syncthing.service=syncthing
      - traefik.http.services.syncthing.loadbalancer.server.port=8384
    hostname: racknerd_syncthing
    security_opt:
      - no-new-privileges:true

networks:
  proxy:
    name: proxy
    external: true
    enable_ipv4: true
    enable_ipv6: true
