---
name: syncthing
services:
  syncthing:
    image: syncthing/syncthing:1.29.1
    container_name: syncthing
    volumes:
      - ./config:/var/syncthing/config
      - /mnt/backup/:/var/syncthing/nextcloud
      - /home/jackstockley/infrastructure/docker/racknerd/:/var/syncthing/docker
    environment:
      - TZ=America/Chicago
      - PUID=0
      - PGID=0
    ports:
      - '0.0.0.0:8384:8384'
    networks:
      - syncthing
      - wireguard
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:8384/rest/noauth/health || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 100s
    labels:
      - traefik.enable=true
      - traefik.http.routers.syncthing.entrypoints=websecure
      - traefik.http.routers.syncthing.rule=Host(`backup.jstockley.com`)
      - traefik.http.routers.syncthing.tls=true
      - traefik.http.routers.syncthing.tls.certresolver=production
      - traefik.http.routers.syncthing.service=syncthing
      - traefik.http.services.syncthing.loadbalancer.server.port=8384
      - traefik.docker.network=syncthing
    deploy:
      resources:
        limits:
          memory: 512M
    hostname: racknerd_syncthing
    security_opt:
      - no-new-privileges:true

networks:
  syncthing:
    name: syncthing
    external: true
  wireguard:
    name: wireguard
    external: true
