services:
  syncthing:
    image: syncthing/syncthing:1.28.0
    container_name: syncthing
    hostname: racknerd_syncthing
    networks:
      - syncthing
      - wireguard
    environment:
      - TZ=America/Chicago
      - PUID=0
      - PGID=0
    volumes:
      - ./config:/var/syncthing/config
      - /mnt/backup/:/var/syncthing/nextcloud
      - /home/jackstockley/infrastructure/docker/racknerd/:/var/syncthing/docker
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.syncthing.entrypoints=websecure
      - traefik.http.routers.syncthing.rule=Host(`backup.jstockley.com`)
      - traefik.http.routers.syncthing.tls=true
      - traefik.http.routers.syncthing.tls.certresolver=production
      - traefik.http.routers.syncthing.service=syncthing
      - traefik.http.services.syncthing.loadbalancer.server.port=8384
      - traefik.docker.network=syncthing

networks:
  syncthing:
    name: syncthing
    external: true
  wireguard:
    name: wireguard
    external: true
