version: "3"
services:
  syncthing:
    image: syncthing/syncthing:1.27.4
    container_name: syncthing
    hostname: syncthing
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /mnt/nc-backup:/var/syncthing/nextcloud
      - /home/jackstockley/infrastructure/docker/racknerd/vaultwarden/vw-data:/var/syncthing/bitwarden
    ports:
      - 8384:8384 # Web UI
      - 22000:22000/tcp # TCP file transfers
      - 22000:22000/udp # QUIC file transfers
      - 21027:21027/udp # Receive local discovery broadcasts
    restart: unless-stopped