---
services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:1.27.5
    container_name: syncthing
    hostname: racknerd
    environment:
      - UMASK=022
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - ./config:/config
      - /mnt/backup/:/data1
      - /home/jackstockley/:/data2
    networks:
      - syncthing
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.syncthing.entrypoints=websecure"
      - "traefik.http.routers.syncthing.rule=Host(`backup.jstockley.com`)"
      - "traefik.http.routers.syncthing.tls=true"
      - "traefik.http.routers.syncthing.tls.certresolver=production"
      - "traefik.http.routers.syncthing.service=syncthing"
      - "traefik.http.services.syncthing.loadbalancer.server.port=8384"
      - "traefik.docker.network=syncthing"

networks:
  syncthing:
    external: true
    name: "syncthing"