services:
  syncthing:
    image: syncthing/syncthing:1.27.6
    container_name: syncthing
    hostname: racknerd
    networks:
      syncthing:
        - ipv4_address: 172.28.0.2
    environment:
      - TZ=America/Chicago
    volumes:
      - ./config:/var/syncthing/config
      - /mnt/backup/:/var/syncthing/nextcloud
      - /home/jackstockley/infrastructure/:/var/syncthing/home
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.syncthing.entrypoints=websecure
      - traefik.http.routers.syncthing.rule=Host(`backup.jstockley.com`)
      - traefik.http.routers.syncthing.tls=true
      - traefik.http.routers.syncthing.tls.certresolver=production
      - traefik.http.routers.syncthing.service=syncthing
      - traefik.http.services.syncthing.loadbalancer.server.port=8384
      - traefik.docker.network=syncthing

networks:
  syncthing:
    external: true
    name: syncthing