---
services:
  syncthing:
    image: syncthing/syncthing:1.27.6
    container_name: syncthing
    hostname: racknerd
    #user:
    #  1000:1000
    environment:
    #  - PUID=1000
    #  - PGID=1000
      - PCAP=cap_chown,cap_fowner+ep
      - TZ=America/Chicago
   # volumes:
     # - syncthing:/var/syncthing/config
    #  - "syncthing:/var/syncthing/config"
    #  - ./config:/var/syncthing/config
    #  - /mnt/backup/:/var/syncthing/nextcloud
    #  - /home/jackstockley/:/var/syncthing/home
    networks:
      - syncthing
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.syncthing.entrypoints=websecure"
      - "traefik.http.routers.syncthing.rule=Host(`backup.jstockley.com`)"
      - "traefik.http.routers.syncthing.tls=true"
      - "traefik.http.routers.syncthing.tls.certresolver=production"
      - "traefik.http.routers.syncthing.service=syncthing"
      - "traefik.http.services.syncthing.loadbalancer.server.port=8384"
      - "traefik.docker.network=syncthing"

#volumes:
#  syncthing:
 #   name: "syncthing"
#    external: true

networks:
  syncthing:
    external: true
    name: "syncthing"