---
name: wireguard
services:
  wireguard:
    image: linuxserver/wireguard:1.0.20250521@sha256:1bf21d1c8933f7376da97bb14a459ae18e716e49d2e3456dbfd71414f60a319a
    container_name: wireguard
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - SERVERURL=iowa.vpn.jstockley.com
      - SERVERPORT=51820
      - PEERS=iphone,ipad,macbook,github,appletv
      - PEERDNS=auto
      - INTERNAL_SUBNET=10.13.13.0
      - ALLOWEDIPS=0.0.0.0/0
      - PERSISTENTKEEPALIVE_PEERS=all
      - LOG_CONFS=true
    ports:
      - '0.0.0.0:51820:51820/udp'
    networks:
      - wireguard
    restart: unless-stopped
    healthcheck:
      test: curl --fail https://google.com || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 100s
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    security_opt:
      - no-new-privileges:true
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1

networks:
  wireguard:
    name: wireguard
    external: true
