services:
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:1.23.13-alpine
    environment:
      - TZ=America/Chicago
    networks:
      - uptime-kuma
      - postgres-internal
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - $XDG_RUNTIME_DIR/docker.sock:/var/run/docker.sock:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.uptime-kuma.entrypoints=websecure
      - traefik.http.routers.uptime-kuma.rule=Host(`status.jstockley.com`)
      - traefik.http.routers.uptime-kuma.tls=true
      - traefik.http.routers.uptime-kuma.tls.certresolver=production
      - traefik.http.routers.uptime-kuma.service=uptime-kuma
      - traefik.http.services.uptime-kuma.loadbalancer.server.port=3001
      - traefik.docker.network=uptime-kuma

networks:
  uptime-kuma:
    external: true
    name: uptime-kuma
  postgres-internal:
    external: true
    name: postgres-internal
