---
name: wireguard
services:
  wireguard:
    image: linuxserver/wireguard:1.0.20250521@sha256:f33891344345b1f78705e723b633e3a3f94d08ae75ca1a5f48c5a449c35bf460
    container_name: wireguard
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - SERVERURL=vpn.jstockley.com
      - SERVERPORT=51820
      - PEERS=iphone,ipad,macbook,github,appletv,beszel
      - PEERDNS=auto
      - INTERNAL_SUBNET=10.13.13.0
      - ALLOWEDIPS=0.0.0.0/0
      - PERSISTENTKEEPALIVE_PEERS=all
      - LOG_CONFS=false
    ports:
      - '0.0.0.0:51820:51820/udp'
    networks:
      - private
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    security_opt:
      - no-new-privileges:true
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1

networks:
  private:
    name: private
    internal: true
    external: true
    enable_ipv4: true
    enable_ipv6: true
