---
name: n8n
services:
  n8nio:
    image: n8nio/n8n:2.28.1
    container_name: n8n
    volumes:
      - ./data:/home/node/.n8n
    environment:
      - N8N_RUNNERS_ENABLED=true
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - TZ=America/Chicago
      - GENERIC_TIMEZONE=America/Chicago
    env_file:
      - .env
    networks:
      - proxy
      - private
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.n8n.entrypoints=websecure
      - traefik.http.routers.n8n.rule=Host(`n8n.local.jstockley.com`) || Host(`n8n.jstockley.com`)
      - traefik.http.routers.n8n.tls=true
      - traefik.http.routers.n8n.tls.certresolver=production
      - traefik.http.routers.n8n.service=n8n
      - traefik.http.services.n8n.loadbalancer.server.port=5678
      - traefik.docker.network=proxy

networks:
  proxy:
    name: proxy
    external: true
    enable_ipv4: true
    enable_ipv6: true
  private:
    name: private
    internal: true
    external: true
    enable_ipv4: true
    enable_ipv6: true
