---
name: it-tools
services:
  it-tools:
    image: corentinth/it-tools:2024.10.22-7ca5933
    container_name: it-tools
    networks:
      - proxy
    restart: unless-stopped
    healthcheck:
      test: curl -f http://localhost
      interval: 60s
      retries: 3
      start_period: 20s
      timeout: 10s
    labels:
      - traefik.enable=true
      - traefik.http.routers.it-tools.entrypoints=websecure
      - traefik.http.routers.it-tools.rule=Host(`it-tools.jstockley.com`)
      - traefik.http.routers.it-tools.tls=true
      - traefik.http.routers.it-tools.tls.certresolver=production
      - traefik.http.routers.it-tools.service=it-tools
      - traefik.http.services.it-tools.loadbalancer.server.port=80
      - traefik.docker.network=it-tools
    security_opt:
      - no-new-privileges:true

networks:
  proxy:
    name: proxy
    external: true
