---
name: postgres
services:
  pg-admin:
    image: dpage/pgadmin4:8.14.0
    container_name: pgadmin
    depends_on:
      - postgres
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    environment:
      - TZ=America/Chicago
    env_file:
      - .env
    networks:
      - postgres
      - pgadmin
      - wireguard
    restart: unless-stopped
    healthcheck:
      test: wget -nv -t 1 --spider http://localhost:80/misc/ping || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    labels:
      - traefik.enable=true
      - traefik.http.routers.pgadmin.entrypoints=websecure
      - traefik.http.routers.pgadmin.rule=Host(`pgadmin.jstockley.com`)
      - traefik.http.routers.pgadmin.tls=true
      - traefik.http.routers.pgadmin.tls.certresolver=production
      - traefik.http.routers.pgadmin.service=pgadmin
      - traefik.http.services.pgadmin.loadbalancer.server.port=80
      - traefik.docker.network=pgadmin
    deploy:
      resources:
        limits:
          memory: 256M
    security_opt:
      - no-new-privileges:true

  postgres:
    image: postgres:17.2-alpine3.21
    container_name: postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - TZ=America/Chicago
    env_file:
      - .env
    networks:
      - postgres
      - wireguard
    restart: unless-stopped
    healthcheck:
      test: pg_isready -U jackstockley
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    deploy:
      resources:
        limits:
          memory: 256M
    security_opt:
      - no-new-privileges:true

networks:
  postgres:
    name: postgres
    external: true
  pgadmin:
    external: true
    name: pgadmin
  wireguard:
    name: wireguard
    external: true
