services:
  postgres-db:
    image: postgres:16.3-alpine3.19
    container_name: postgres
    networks:
      - postgres-internal
    env_file:
      - ./.env
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - TZ=America/Chicago
    restart: unless-stopped
    healthcheck:
      test:
        - CMD
        - pg_isready
        - -U
        - jackstockley
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

  pg-admin:
    image: dpage/pgadmin4:8.7
    depends_on:
      - postgres-db
    container_name: pgadmin
    env_file:
      - ./.env
    networks:
      - postgres-internal
      - postgres-external
    environment:
      - TZ=America/Chicago
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.pgadmin.entrypoints=websecure
      - traefik.http.routers.pgadmin.rule=Host(`pgadmin.jstockley.com`)
      - traefik.http.routers.pgadmin.tls=true
      - traefik.http.routers.pgadmin.tls.certresolver=production
      - traefik.http.routers.pgadmin.service=pgadmin
      - traefik.http.services.pgadmin.loadbalancer.server.port=80
      - traefik.docker.network=postgres-external
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:80/misc/ping || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

networks:
  postgres-internal:
    external: true
    name: postgres-internal
    ipam:
      driver: default
      config:
        - subnet: 172.19.1.0/24
  postgres-external:
    external: true
    name: postgres-external
    ipam:
      driver: default
      config:
        - subnet: 172.18.5.0/24