---
services:
  nextcloud:
    image: nextcloud/all-in-one:20241017_085101
    restart: unless-stopped
    container_name: nextcloud-aio-mastercontainer
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - nextcloud-aio
      - wireguard
    environment:
      - APACHE_PORT=11000
      - APACHE_IP_BINDING=127.0.0.1

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer

networks:
  nextcloud-aio:
    name: nextcloud-aio
    external: true
  wireguard:
    name: wireguard
    external: true