# dclint disable service-image-require-explicit-tag
---
name: nextcloud
services:
  nextcloud:
    image: nextcloud/all-in-one:latest
    container_name: nextcloud-aio-mastercontainer
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - APACHE_PORT=11000
      - APACHE_IP_BINDING=127.0.0.1
    networks:
      - nextcloud-aio
      - wireguard
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://nextcloud-aio-apache:11000 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

networks:
  nextcloud-aio:
    name: nextcloud-aio
    external: true
  wireguard:
    name: wireguard
    external: true

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer
