version: "3.6"

services:
  nextcloud:
    image: "nextcloud/all-in-one:latest"
    restart: "unless-stopped"
    container_name: "nextcloud-aio-mastercontainer"
    volumes:
      - "nextcloud_aio_mastercontainer:/mnt/docker-aio-config"
      - "$XDG_RUNTIME_DIR/docker.sock:/var/run/docker.sock:ro"
    ports:
      - "8080:8080"
    environment:
      - "APACHE_PORT=11000"
      - "WATCHTOWER_DOCKER_SOCKET_PATH=$XDG_RUNTIME_DIR/docker.sock"

volumes:
  nextcloud_aio_mastercontainer:
    name: "nextcloud_aio_mastercontainer"