---
name: vaultwarden
services:
  vaultwarden:
    image: vaultwarden/server:1.32.7-alpine
    container_name: vaultwarden
    volumes:
      - ./data:/data
    environment:
      - TZ=America/Chicago
    env_file:
      - .env
    networks:
      - vaultwarden
      - postgres
      - wireguard
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:80/alive || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 100s
    labels:
      - traefik.enable=true
      - traefik.http.routers.vaultwarden.entrypoints=websecure
      - traefik.http.routers.vaultwarden.rule=Host(`vault.jstockley.com`)
      - traefik.http.routers.vaultwarden.tls=true
      - traefik.http.routers.vaultwarden.tls.certresolver=production
      - traefik.http.routers.vaultwarden.service=vaultwarden
      - traefik.http.services.vaultwarden.loadbalancer.server.port=80
      - traefik.docker.network=vaultwarden
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true

networks:
  vaultwarden:
    name: vaultwarden
    external: true
  postgres:
    name: postgres
    external: true
  wireguard:
    name: wireguard
    external: true
