services:
  vaultwarden:
    container_name: vaultwarden
    env_file:
      - ./.env
    environment:
      - TZ=America/Chicago
    image: vaultwarden/server:1.32.3
    networks:
      - vaultwarden
      - postgres-internal
    restart: unless-stopped
    volumes:
      - ./data:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.vaultwarden.entrypoints=websecure
      - traefik.http.routers.vaultwarden.rule=Host(`vault.jstockley.com`)
      - traefik.http.routers.vaultwarden.tls=true
      - traefik.http.routers.vaultwarden.tls.certresolver=production
      - traefik.http.routers.vaultwarden.service=vaultwarden
      - traefik.http.services.vaultwarden.loadbalancer.server.port=80
      - traefik.docker.network=vaultwarden

networks:
  vaultwarden:
    external: true
    name: vaultwarden
    ipam:
      driver: default
      config:
        - subnet: 172.18.1.0/24
  postgres-internal:
    external: true
    name: postgres-internal
    ipam:
      driver: default
      config:
        - subnet: 172.19.1.0/24