version: "3.6"

services:
  vaultwarden:
    container_name: "vaultwarden"
    environment:
      - "ADMIN_TOKEN=${{ secrets.ADMIN_TOKEN }}"
      - "DOMAIN=https://vault.jstockley.com"
      - "DUO_HOST=api-c8dece9f.duosecurity.com"
      - "DUO_IKEY=${{ secrets.DUO_IKEY }}"
      - "DUO_SKEY=${{ secrets.DUO_SKEY }}"
      - "EMAIL_ATTEMPTS_LIMIT=3"
      - "EMAIL_EXPIRATION_TIME=600"
      - "EMERGENCY_ACCESS_ALLOWED=true"
      - "ROCKET_ADDRESS=0.0.0.0"
      - "ROCKET_PORT=80"
      - "ROCKET_PROFILE=release"
      - "SENDS_ALLOWED=true"
      - "SIGNUPS_DOMAINS_WHITELIST=jstockley.com"
      - "SIGNUPS_VERIFY=true"
      - "SIGNUPS_VERIFY_RESEND_LIMIT=6"
      - "SIGNUPS_VERIFY_RESEND_TIME=3600"
      - "SMTP_AUTH_MECHANISM=Login"
      - "SMTP_FROM=${{ secrets.SMTP_FROM }}"
      - "SMTP_FROM_NAME=Vaultwarden"
      - "SMTP_HOST=${{ secrets.SMTP_HOST }}"
      - "SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}"
      - "SMTP_PORT=587"
      - "SMTP_SECURITY=starttls"
      - "SMTP_TIMEOUT=15"
      - "SMTP_USERNAME=${{ secrets.SMTP_FROM }}"
      - "WEBSOCKET_ADDRESS=0.0.0.0"
      - "WEBSOCKET_ENABLED=true"
      - "WEBSOCKET_PORT=3012"
    image: "vaultwarden/server:1.30.1"
    networks:
      - "vaultwarden"
    restart: "unless-stopped"
    volumes:
      - "/home/jackstockley/docker/vaultwarden/vw-data:/data"

networks:
  vaultwarden:
    external: true
    name: "vaultwarden"
