---
x-airflow-common: &airflow-common
  image: jnstockley/airflow:2025.05.01
  network_mode: service:wireguard-airflow
  env_file:
    - .env
  environment: &airflow-common-env
    AIRFLOW__WEBSERVER__BASE_URL: https://airflow.local.jstockley.com
    TZ: America/Chicago
    AIRFLOW__CORE__DEFAULT_TIMEZONE: America/Chicago
    AIRFLOW__WEBSERVER__DEFAULT_UI_TIMEZONE: America/Chicago
    AIRFLOW__CORE__EXECUTION_API_SERVER_URL: http://localhost:8080/execution/
    AIRFLOW_VAR_ENV: prod
    REDIS_URI: redis://redis:6379/0
    AUTHENTIK_APP_NANE: airflow-internal
    AIRFLOW__CORE__AUTH_MANAGER: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
    AIRFLOW_CONFIG: '/opt/airflow/config/airflow.cfg'
  volumes:
    - ./logs:/opt/airflow/logs
    - ./af-config:/opt/airflow/config
    - ./data:/opt/airflow/data

name: airflow
services:
  airflow-apiserver:
    container_name: airflow-api-server
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    command: api-server
    restart: always
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/api/v2/version"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    labels:
      - traefik.enable=true
      - traefik.http.routers.airflow.entrypoints=websecure
      - traefik.http.routers.airflow.rule=Host(`airflow.local.jstockley.com`)
      - traefik.http.routers.airflow.tls=true
      - traefik.http.routers.airflow.tls.certresolver=production
      - traefik.http.routers.airflow.service=airflow
      - traefik.http.services.airflow.loadbalancer.server.port=8080
    <<: *airflow-common

  airflow-dag-processor:
    container_name: airflow-dag-processor
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    command: dag-processor
    restart: always
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'airflow jobs check --job-type DagProcessorJob --hostname
            "$${HOSTNAME}"'
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    <<: *airflow-common

  airflow-init:
    container_name: airflow-init
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_MIGRATE: 'true'
    env_file:
      - .env
    command: version
    <<: *airflow-common

  airflow-scheduler:
    container_name: airflow-scheduler
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    command: scheduler
    restart: always
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8974/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    <<: *airflow-common

  airflow-triggerer:
    container_name: airflow-triggerer
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    command: triggerer
    restart: always
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'airflow jobs check --job-type TriggererJob --hostname
            "$${HOSTNAME}"'
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    <<: *airflow-common

  wireguard-airflow:
    image: linuxserver/wireguard:1.0.20210914@sha256:7792dcef56c51e6b4d499a209e980ed74309bf3bee6af12168ea02bf289eddd9
    container_name: wireguard-airflow
    volumes:
      - ./config:/config/wg_confs
      - /lib/modules:/lib/modules
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    networks:
      - proxy
      - private
    restart: unless-stopped
    healthcheck:
      test: curl --fail https://google.com || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 100s
    logging:
      driver: loki
      options:
        loki-url: "https://loki.local.jstockley.com/loki/api/v1/push"
        loki-retries: 2
        loki-max-backoff: 800ms
        loki-timeout: 1s
        keep-file: "true"
        mode: "non-blocking"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    security_opt:
      - no-new-privileges:true
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1

networks:
  proxy:
    name: proxy
    external: true
  private:
    name: private
    internal: true
    external: true
