services:
  airflow-webserver:
    image: jnstockley/airflow:78bc748e01c17e87b6cc563e8f47cdaed9030091
    volumes:
      - ./logs:/opt/airflow/logs
      - ./data:/opt/airflow/data
    env_file:
      .env
    networks:
      - airflow
      - postgres
      - wireguard
    command: webserver
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 100s
    restart: unless-stopped
    container_name: airflow-webserver
    depends_on:
      - airflow-scheduler
    labels:
      - traefik.enable=true
      - traefik.http.routers.airflow.entrypoints=websecure
      - traefik.http.routers.airflow.rule=Host(`airflow.local.jstockley.com`)
      - traefik.http.routers.airflow.tls=true
      - traefik.http.routers.airflow.tls.certresolver=production
      - traefik.http.routers.airflow.service=airflow
      - traefik.http.services.airflow.loadbalancer.server.port=8080
      - traefik.docker.network=airflow

  airflow-scheduler:
    image: jnstockley/airflow:78bc748e01c17e87b6cc563e8f47cdaed9030091
    volumes:
      - ./logs:/opt/airflow/logs
      - ./data:/opt/airflow/data
    env_file:
      .env
    networks:
      - airflow
      - postgres
      - wireguard
    command: scheduler
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8974/health" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 100s
    restart: unless-stopped
    container_name: airflow-scheduler
    depends_on:
      - airflow-init

  airflow-init:
    image: jnstockley/airflow:78bc748e01c17e87b6cc563e8f47cdaed9030091
    volumes:
      - ./logs:/opt/airflow/logs
      - ./data:/opt/airflow/data
    env_file:
      .env
    networks:
      - airflow
      - postgres
      - wireguard
    command: version
    environment:
      _AIRFLOW_DB_MIGRATE: 'true'

networks:
  airflow:
    name: airflow
    external: true
  postgres:
    name: postgres
    external: true
  wireguard:
    name: wireguard
    external: true
