x-airflow-common:
  &airflow-common
  image: jnstockley/airflow:2f67147f8a7fc1cb75ede53e86416a077dabcd02
  volumes:
    - ./logs:/opt/airflow/logs
    - ./data:/opt/airflow/data
  env_file:
    - .env
  networks:
    - airflow
    - postgres-internal

services:
  airflow-webserver:
    <<: *airflow-common
    command: webserver
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 100s
    restart: always
    container_name: airflow-webserver
    depends_on:
      - airflow-scheduler
    ports:
      - "8082:8080"

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8974/health" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 100s
    restart: always
    container_name: airflow-scheduler
    depends_on:
      - airflow-init

  airflow-init:
    <<: *airflow-common
    command: version
    environment:
      _AIRFLOW_DB_MIGRATE: 'true'

networks:
  airflow:
    external: true
  postgres-internal:
    external: true