---
name: airflow
services:
  airflow-init:
    image: jnstockley/airflow:2024.12.28
    depends_on:
      - wireguard-airflow
    volumes:
      - ./logs:/opt/airflow/logs
      - ./data:/opt/airflow/data
    environment:
      _AIRFLOW_DB_MIGRATE: 'true'
    env_file: .env
    network_mode: service:wireguard-airflow
    command: version

  airflow-scheduler:
    image: jnstockley/airflow:2024.12.28
    container_name: airflow-scheduler
    depends_on:
      - airflow-init
      - wireguard-airflow
    volumes:
      - ./logs:/opt/airflow/logs
      - ./data:/opt/airflow/data
    env_file: .env
    network_mode: service:wireguard-airflow
    command: scheduler
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:8974/health || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 100s
  airflow-webserver:
    image: jnstockley/airflow:2024.12.28
    container_name: airflow-webserver
    depends_on:
      - airflow-scheduler
      - wireguard-airflow
    volumes:
      - ./logs:/opt/airflow/logs
      - ./data:/opt/airflow/data
    env_file: .env
    network_mode: service:wireguard-airflow
    command: webserver
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:8080/health || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 100s
    labels:
      - traefik.enable=true
      - traefik.http.routers.airflow.entrypoints=websecure
      - traefik.http.routers.airflow.rule=Host(`airflow.local.jstockley.com`)
      - traefik.http.routers.airflow.tls=true
      - traefik.http.routers.airflow.tls.certresolver=production
      - traefik.http.routers.airflow.service=airflow
      - traefik.http.services.airflow.loadbalancer.server.port=8080
      - traefik.docker.network=airflow
  wireguard-airflow:
    image: linuxserver/wireguard:1.0.20210914@sha256:5a0a72a7bc7f08b2989ad95174a4bba275c3fda7ffac47988cfe5e8c1d45096d
    container_name: wireguard-airflow
    volumes:
      - ./config:/config/wg_confs
      - /lib/modules:/lib/modules # optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    networks:
      - airflow
      - postgres
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1

networks:
  airflow:
    name: airflow
    external: true
  postgres:
    name: postgres
    external: true
