services:
  redis:
    image: redis:7.2.5-alpine
    environment:
      - TZ=America/Chicago
    container_name: redis
    command: --save 60 1 --loglevel warning
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    volumes:
      - ./data/:/data
    networks:
      - redis

networks:
  redis:
    name: redis
    external: true
    ipam:
      driver: default
      config:
        - subnet: 172.19.2.0/24
