---
name: redis
services:
  redis:
    image: redis:8.0.3-alpine
    container_name: redis
    volumes:
      - ./data/:/data
    environment:
      - TZ=America/Chicago
    networks:
      - redis
      - wireguard
    command: --save 60 1 --loglevel warning
    restart: unless-stopped
    healthcheck:
      test: redis-cli ping | grep PONG
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    deploy:
      resources:
        limits:
          memory: 256M
    security_opt:
      - no-new-privileges:true

networks:
  redis:
    name: redis
    external: true
  wireguard:
    name: wireguard
    external: true
