---
name: minio
services:
  minio:
    image: quay.io/minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: minio
    volumes:
      - ./data:/data
    environment:
      - TZ=America/Chicago
    env_file:
      - .env
    networks:
      - proxy
    command: 'server /data --console-address ":9001"'
    logging:
      driver: loki
      options:
        loki-url: "https://loki.local.jstockley.com/loki/api/v1/push"
        loki-retries: 2
        loki-max-backoff: 800ms
        loki-timeout: 1s
        keep-file: "true"
        mode: "non-blocking"
    labels:
      - traefik.enable=true
      - traefik.http.routers.minio.entrypoints=websecure
      - traefik.http.routers.minio.rule=Host(`s3.jstockley.com`)
      - traefik.http.routers.minio.tls=true
      - traefik.http.routers.minio.tls.certresolver=production
      - traefik.http.routers.minio.service=minio
      - traefik.http.services.minio.loadbalancer.server.port=9000

networks:
  proxy:
    name: proxy
    external: true
