---
name: cloudflared
services:
  cloudflared:
    image: cloudflare/cloudflared:2024.11.1
    container_name: cloudflared
    environment:
      - TZ=America/Chicago
    env_file:
      - .env
    networks:
      - traefik
      - nextcloud-aio
    command: tunnel run
    restart: unless-stopped

networks:
  nextcloud-aio:
    name: nextcloud-aio
    external: true
  traefik:
    name: traefik
    external: true
