---
name: cloudflared
services:
  cloudflared:
    image: cloudflare/cloudflared:2026.7.2
    container_name: cloudflared
    environment:
      - TZ=America/Chicago
    env_file:
      - .env
    networks:
      - proxy
    command: tunnel --metrics localhost:3333 run
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

networks:
  proxy:
    name: proxy
    external: true
    enable_ipv4: true
    enable_ipv6: true
