---
name: cloudflared
services:
  cloudflared:
    image: cloudflare/cloudflared:2024.12.2
    container_name: cloudflared
    environment:
      - TZ=America/Chicago
    env_file:
      - .env
    networks:
      - traefik
      - nextcloud-aio
    command: tunnel run -metrics localhost:3333
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:3333 || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 100s

networks:
  nextcloud-aio:
    name: nextcloud-aio
    external: true
  traefik:
    name: traefik
    external: true
