services:
  cloudflared:
    image: cloudflare/cloudflared:2024.11.0
    container_name: cloudflared
    env_file:
      - .env
    environment:
      - TZ=America/Chicago
    networks:
      - traefik
      - nextcloud-aio
    restart: unless-stopped
    command: tunnel run

networks:
  nextcloud-aio:
    name: nextcloud-aio
    external: true
  traefik:
    name: traefik
    external: true