services:
  cloudflared:
    image: cloudflare/cloudflared:2024.9.1
    container_name: cloudflared
    env_file:
      - ./.env
    environment:
      - TZ=America/Chicago
    networks:
      - traefik
      - nextcloud-aio
    restart: unless-stopped
    command: tunnel run

networks:
  nextcloud-aio:
    external: true
    name: nextcloud-aio
    ipam:
      driver: default
      config:
        - subnet: 172.18.2.0/24
  traefik:
    external: true
    name: traefik
    ipam:
      driver: default
      config:
        - subnet: 172.18.3.0/24