---
name: cloudflared
services:
  cloudflared:
    image: cloudflare/cloudflared:2025.1.1
    container_name: cloudflared
    environment:
      - TZ=America/Chicago
    env_file:
      - .env
    networks:
      - traefik
      - nextcloud-aio
    command: tunnel --metrics localhost:3333 run
    restart: unless-stopped
    healthcheck:
      test: tunnel --metrics localhost:3333 ready
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 128M
    security_opt:
      - no-new-privileges:true

networks:
  nextcloud-aio:
    name: nextcloud-aio
    external: true
  traefik:
    name: traefik
    external: true
