services:
  cloudflared:
    image: cloudflare/cloudflared:2024.4.0
    container_name: cloudflared
    env_file:
      - ./.env
    environment:
      - TZ=America/Chicago
    networks:
      - traefik
      - nextcloud-aio
    restart: unless-stopped
    command: tunnel run
    healthcheck:
      test: ["CMD", "cloudflared", "tunnel", "health"]
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

networks:
  nextcloud-aio:
    external: true
    name: "nextcloud-aio"
  traefik:
    external: true
    name: "traefik"