services:
  cloudflared:
    image: cloudflare/cloudflared:2024.3.0
    container_name: cloudflared
    env_file:
      - path: ./.env
        required: true
    environment:
      - TZ=America/Chicago
    networks:
      - traefik
      - nextcloud-aio
    restart: unless-stopped
    command: tunnel run

networks:
  nextcloud-aio:
    external: true
    name: "nextcloud-aio"
  traefik:
    external: true
    name: "traefik"