services:
  dockge:
    image: "louislam/dockge:1.4.2"
    restart: "unless-stopped"
    volumes:
      - "./data:/app/data"
      - "$XDG_RUNTIME_DIR/docker.sock:/var/run/docker.sock"
      - "/home/jackstockley/infrastructure/docker/racknerd:/home/jackstockley/infrastructure/docker/racknerd"
    environment:
      - "DOCKGE_STACKS_DIR=/home/jackstockley/infrastructure/docker/racknerd"
    networks:
       - "dockge"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dockge.entrypoints=websecure"
      - "traefik.http.routers.dockge.rule=Host(`docker.jstockley.com`)"
      - "traefik.http.routers.dockge.tls=true"
      - "traefik.http.routers.dockge.tls.certresolver=production"
      - "traefik.http.routers.dockge.service=dockge"
      - "traefik.http.services.dockge.loadbalancer.server.port=8384"
      - "traefik.docker.network=dockge"


networks:
  dockge:
    name: "dockge"
    external: true