version: "3.8"

services:
  dockge:
    image: "louislam/dockge:1.4.1"
    restart: "unless-stopped"
    volumes:
      - "./data:/app/data"
      - "$XDG_RUNTIME_DIR/docker.sock:/var/run/docker.sock"
      - "/home/jackstockley/infrastructure/docker/racknerd:/home/jackstockley/infrastructure/docker/racknerd"
    environment:
      - "DOCKGE_STACKS_DIR=/home/jackstockley/infrastructure/docker/racknerd"
    networks:
       - "dockge"

networks:
  dockge:
    name: "dockge"
    external: true