services:
  web-scrapper:
    container_name: web_scrapper
    image: jnstockley/web-scrapper:2024.09.24
    working_dir: /web-scrapper
    env_file:
      - .env
    environment:
      - TZ=America/Chicago
    restart: always
    volumes:
      - ./config.toml:/web-scrapper/config.toml
      - ./data/:/web-scrapper/data/
