services:
  web-scrapper:
    container_name: web_scrapper
    image: jnstockley/web-scrapper:2024.11.06
    working_dir: /web-scrapper
    env_file:
      - .env
    environment:
      - TZ=America/Chicago
    restart: unless-stopped
    volumes:
      - ./config.toml:/web-scrapper/config.toml
      - ./data/:/web-scrapper/data/
