---
name: web-scrapper
services:
  web-scrapper:
    image: jnstockley/web-scrapper:v0.2.0
    container_name: web_scrapper
    volumes:
      - ./data/:/web-scrapper/data/
    environment:
      - TZ=America/Chicago
    env_file:
      - .env
    restart: unless-stopped
