---
name: web-scrapper
services:
  web-scrapper:
    image: jnstockley/web-scrapper:2024.11.06
    container_name: web_scrapper
    volumes:
      - ./config.toml:/web-scrapper/config.toml
      - ./data/:/web-scrapper/data/
    environment:
      - TZ=America/Chicago
    env_file:
      - .env
    working_dir: /web-scrapper
    restart: unless-stopped
