---
name: rustdesk
services:
  hbbr:
    image: rustdesk/rustdesk-server:1.1.14
    container_name: hbbr
    volumes:
      - ./data:/root
    ports:
      - '0.0.0.0:21117:21117/tcp'
    command: hbbr
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
  hbbs:
    image: rustdesk/rustdesk-server:1.1.14
    container_name: hbbs
    depends_on:
      - hbbr
    volumes:
      - ./data:/root
    ports:
      - '0.0.0.0:21115:21115/tcp'
      - '0.0.0.0:21116:21116'
    command: hbbs
    restart: unless-stopped
    logging:
      driver: loki
      options:
        loki-url: "https://loki.local.jstockley.com/loki/api/v1/push"
        loki-retries: 2
        loki-max-backoff: 800ms
        loki-timeout: 1s
        keep-file: "true"
        mode: "non-blocking"
    security_opt:
      - no-new-privileges:true
