---
name: tailscale
services:
  tailscale:
    image: tailscale/tailscale:v1.80.3
    container_name: tailscale
    volumes:
      - /dev/net/tun:/dev/net/tun
      - ./data:/var/lib/tailscale
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_EXTRA_ARGS=--advertise-exit-node --advertise-tags=tag:container
        --advertise-routes=172.0.0.0/8
      - TZ=America/Chicago
    env_file:
      - .env
    networks:
      - tailscale
    restart: unless-stopped
    healthcheck:
      test: ping -c 3 photo_server
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    logging:
      driver: loki
      options:
        loki-url: "https://loki.local.jstockley.com/loki/api/v1/push"
        loki-retries: 2
        loki-max-backoff: 800ms
        loki-timeout: 1s
        keep-file: "true"
        mode: "non-blocking"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    hostname: tailscale_photo_server
    security_opt:
      - no-new-privileges:true

networks:
  tailscale:
    external: true
    name: tailscale
