services:
  traefik:
    image: traefik:v3.1.3
    container_name: traefik
    ports:
      - 80:80
      - 443:443
      # -- (Optional) Enable Dashboard, don't do in production
      # - 8080:8080
    environment:
      - TZ=America/Chicago
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./config/conf/:/etc/traefik/conf/
      - ./config/certs/:/etc/traefik/certs/
      - ./logs/:/var/log/traefik/
    # -- (Optional) When using Cloudflare as Cert Resolver
    # environment:
    #   - CF_DNS_API_TOKEN=your-cloudflare-api-token
    # -- (Optional) When using a custom network
    networks:
      adguard:
        ipv4_address: 172.18.0.2
      vaultwarden:
      nextcloud-aio:
      traefik:
      uptime-kuma:
      postgres-external:
      api:
      dockge:
      syncthing:
        ipv4_address: 172.18.8.2
      gitea:
      authentik:
      airflow:
      tailscale:
    restart: unless-stopped
    healthcheck:
      test:
        - CMD
        - traefik
        - healthcheck
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

networks:
  adguard:
    external: true
    name: adguard
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24
  vaultwarden:
    external: true
    name: vaultwarden
    ipam:
      driver: default
      config:
        - subnet: 172.18.1.0/24
  nextcloud-aio:
    external: true
    name: nextcloud-aio
    ipam:
      driver: default
      config:
        - subnet: 172.18.2.0/24
  traefik:
    external: true
    name: traefik
    ipam:
      driver: default
      config:
        - subnet: 172.18.3.0/24
  uptime-kuma:
    external: true
    name: uptime-kuma
    ipam:
      driver: default
      config:
        - subnet: 172.18.4.0/24
  postgres-external:
    external: true
    name: postgres-external
    ipam:
      driver: default
      config:
        - subnet: 172.18.5.0/24
  api:
    external: true
    name: api
    ipam:
      driver: default
      config:
        - subnet: 172.18.6.0/24
  dockge:
    name: dockge
    external: true
    ipam:
      driver: default
      config:
        - subnet: 172.18.7.0/24
  syncthing:
    name: syncthing
    external: true
    ipam:
      driver: default
      config:
        - subnet: 172.18.8.0/24
  gitea:
    external: true
    name: gitea
    ipam:
      driver: default
      config:
        - subnet: 172.18.9.0/24
  authentik:
    external: true
    name: authentik
    ipam:
      driver: default
      config:
        - subnet: 172.18.10.0/24
  airflow:
    external: true
    name: airflow
    ipam:
      driver: default
      config:
        - subnet: 172.18.11.0/24
  tailscale:
    external: true
    name: tailscale
    ipam:
      driver: default
      config:
        - subnet: 172.19.3.0/24
