services:
  traefik:
    image: traefik:v3.2.0
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
      - "51820:51820/udp"
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./config/conf/:/etc/traefik/conf/
      - ./config/certs/:/etc/traefik/certs/
      - ./logs/:/var/log/traefik/
    networks:
      - adguard
      - vaultwarden
      - nextcloud-aio
      - traefik
      - uptime-kuma
      - pgadmin
      - api
      - syncthing
      - authentik
      - airflow
      - tailscale
      - wireguard
    restart: unless-stopped
    healthcheck:
      test: traefik healthcheck
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

networks:
  adguard:
    name: adguard
    external: true
  vaultwarden:
    name: vaultwarden
    external: true
  nextcloud-aio:
    name: nextcloud-aio
    external: true
  traefik:
    name: traefik
    external: true
  uptime-kuma:
    name: uptime-kuma
    external: true
  pgadmin:
    name: pgadmin
    external: true
  api:
    name: api
    external: true
  syncthing:
    external: true
    name: syncthing
  authentik:
    name: authentik
    external: true
  airflow:
    name: airflow
    external: true
  tailscale:
    name: tailscale
    external: true
  wireguard:
    name: wireguard
    external: true
