services:
  traefik:
    image: traefik:v2.11.0
    container_name: traefik
    ports:
      - 80:80
      - 443:443
      # -- (Optional) Enable Dashboard, don't do in production
      # - 8080:8080
    environment:
      - TZ=America/Chicago
    volumes:
      - $XDG_RUNTIME_DIR/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./config/conf/:/etc/traefik/conf/
      - ./config/certs/:/etc/traefik/certs/
#      - traefik-certs:/etc/traefik/certs/
    # -- (Optional) When using Cloudflare as Cert Resolver
    # environment:
    #   - CF_DNS_API_TOKEN=your-cloudflare-api-token
    # -- (Optional) When using a custom network
    networks:
      - adguard
      - vaultwarden
      - nextcloud-aio
      - traefik
      - uptime-kuma
      - postgres-external
      - api
      - dockge
    restart: unless-stopped

networks:
  adguard:
    external: true
    name: "adguard"
  vaultwarden:
    external: true
    name: "vaultwarden"
  nextcloud-aio:
    external: true
    name: "nextcloud-aio"
  traefik:
    external: true
    name: "traefik"
  uptime-kuma:
    external: true
    name: "uptime-kuma"
  postgres-external:
    external: true
    name: "postgres-external"
  api:
    external: true
    name: api
  dockge:
    name: "dockge"
    external: true
