services:
  traefik:
    image: traefik:v3.0.0
    container_name: traefik
    ports:
      - 80:80
      - 443:443
      # -- (Optional) Enable Dashboard, don't do in production
      # - 8080:8080
    environment:
      - TZ=America/Chicago
    volumes:
      - $XDG_RUNTIME_DIR/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./config/conf/:/etc/traefik/conf/
      - ./config/certs/:/etc/traefik/certs/
      - ./logs/:/var/log/traefik/
    # -- (Optional) When using Cloudflare as Cert Resolver
    # environment:
    #   - CF_DNS_API_TOKEN=your-cloudflare-api-token
    # -- (Optional) When using a custom network
    networks:
      - adguard
      - vaultwarden
      - nextcloud-aio
      - traefik
      - uptime-kuma
      - postgres-external
      - api
      - dockge
      - syncthing
      - gitea
      - authentik
    restart: unless-stopped
    healthcheck:
      test:
        - CMD
        - traefik
        - healthcheck
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

networks:
  adguard:
    external: true
    name: adguard
  vaultwarden:
    external: true
    name: vaultwarden
  nextcloud-aio:
    external: true
    name: nextcloud-aio
  traefik:
    external: true
    name: traefik
  uptime-kuma:
    external: true
    name: uptime-kuma
  postgres-external:
    external: true
    name: postgres-external
  api:
    external: true
    name: api
  dockge:
    name: dockge
    external: true
  syncthing:
    name: syncthing
    external: true
  gitea:
    external: true
    name: gitea
  authentik:
    external: true
    name: authentik
