services:
  gluetun:
    image: qmcgaw/gluetun:v3.38.0
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    ports:
      - 8888:8112 # deluge web interface
      - 58846:58846 # deluge RPC
      - 6789:6789 # nzbget
      - 9696:9696 # prowlarr
    volumes:
      - ./gluetun:/gluetun
    env_file:
      - .env
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 60s
      timeout: 20s
      retries: 5
    restart: unless-stopped

  deluge:
    image: linuxserver/deluge:18.04.1
    container_name: deluge
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Chicago
    volumes:
      - ./deluge:/config
      - ./data/:/data
    network_mode: service:gluetun
  
  nzbget:
    image: lscr.io/linuxserver/nzbget:2021.11.25
    container_name: nzbget
    env_file:
      - .env
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Chicago
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./nzbget:/config
      - ./data:/data
    restart: unless-stopped
    network_mode: service:gluetun
  
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:1.21.2
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Chicago
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./prowlarr:/config
    restart: unless-stopped
    network_mode: service:gluetun
  
  radarr:
    image: lscr.io/linuxserver/radarr:5.8.3
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Chicago
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./radarr:/config
      - ./data:/data
    ports:
      - 7878:7878
  
  lidarr:
    container_name: lidarr
    image: lscr.io/linuxserver/lidarr:8.1.2135
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./lidarr:/config
      - ./data:/data
    environment:
     - PUID=1000
     - PGID=100
       - TZ=America/Chicago
    ports:
      - 8686:8686
  
  bazarr:
    image: lscr.io/linuxserver/bazarr:1.4.3
    container_name: bazarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Chicago
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./bazarr:/config
      - ./data:/data
    ports:
      - 6767:6767