---
name: crowdsec
services:

  bouncer-traefik:
    image: fbonalair/traefik-crowdsec-bouncer:0.5.0
    container_name: bouncer-traefik
    depends_on:
      - proxy
    environment:
      CROWDSEC_BOUNCER_API_KEY: some-api-key
      CROWDSEC_AGENT_HOST: crowdsec:8080
    networks:
      - crowdsec
    restart: unless-stopped
  crowdsec:
    image: crowdsecurity/crowdsec:v1.6.8
    container_name: crowdsec
    volumes:
      - ./config/acquis.yaml:/etc/crowdsec/acquis.yaml
      - crowdsec-db:/var/lib/crowdsec/data/
      - crowdsec-config:/etc/crowdsec/
      - traefik_traefik-logs:/var/log/traefik/:ro
    environment:
      GID: "${GID-1000}"
      COLLECTIONS: "crowdsecurity/linux crowdsecurity/traefik"
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external: true

volumes:
  crowdsec-db:
  crowdsec-config:
  traefik_traefik-logs:
    external: true
