services:
  twingate_connector:
    container_name: photo-server-twingate-connector
    restart: always
    image: twingate/connector:1.70.0
    env_file:
      - .env
    sysctls:
      net.ipv4.ping_group_range: "0 2147483647"