---
name: trivy
services:
  trivy:
    image: aquasec/trivy:0.69.3
    container_name: trivy
    volumes:
      - /:/app:ro
      - ./:/report:rw
    working_dir: /app
    command: ["fs", "--skip-dirs", "var/lib/docker/", "-f", "sarif", "-o", "/report/trivy-results.sarif", "--severity", "CRITICAL,HIGH", "--scanners", "vuln,misconfig", "."]
    restart: 'no'
