---
name: mariadb
services:
  mariadb:
    image: dhi.io/mariadb:12.3.1
    container_name: mariadb
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - TZ=America/Chicago
      - PGTZ=America/Chicago
    env_file:
      - .env
    networks:
      - private
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    security_opt:
      - no-new-privileges:true

  phpmyadmin:
    image: phpmyadmin:5.2.3
    container_name: phpmyadmin
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
    env_file:
      - .env
    networks:
      - proxy
      - private
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/index.php"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.phpmyadmin.entrypoints=websecure
      - traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.jstockley.com`)
      - traefik.http.routers.phpmyadmin.tls=true
      - traefik.http.routers.phpmyadmin.tls.certresolver=production
      - traefik.http.routers.phpmyadmin.service=phpmyadmin
      - traefik.http.services.phpmyadmin.loadbalancer.server.port=80
    security_opt:
      - no-new-privileges:true

networks:
  proxy:
    name: proxy
    external: true
    enable_ipv4: true
    enable_ipv6: true
  private:
    name: private
    internal: true
    external: true
    enable_ipv4: true
    enable_ipv6: true
