---
name: mariadb
services:
  mariadb:
    image: mariadb:12.2.2
    container_name: mariadb
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - TZ=America/Chicago
      - PGTZ=America/Chicago
    env_file:
      - .env
    networks:
      - mariadb
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.3
    container_name: phpmyadmin
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
    env_file:
      - .env
    networks:
      - mariadb
      - phpmyadmin
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.phpmyadmin.entrypoints=websecure
      - traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.jstockley.com`)
      - traefik.http.routers.phpmyadmin.tls=true
      - traefik.http.routers.phpmyadmin.tls.certresolver=production
      - traefik.http.routers.phpmyadmin.service=phpmyadmin
      - traefik.http.services.phpmyadmin.loadbalancer.server.port=80
      - traefik.docker.network=phpmyadmin

networks:
  mariadb:
    name: mariadb
    external: true
  phpmyadmin:
    name: phpmyadmin
    external: true
