---
name: openspeedtest
services:
  speedtest:
    image: openspeedtest/latest:v2.0.6
    container_name: openspeedtest
    networks:
      - private
      # - proxy
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.openspeedtest.entrypoints=websecure
      - traefik.http.routers.openspeedtest.rule=Host(`speed.jstockley.com`) || Host(`speed.local.jstockley.com`)
      - traefik.http.routers.openspeedtest.tls=true
      - traefik.http.routers.openspeedtest.tls.certresolver=production
      - traefik.http.routers.openspeedtest.service=openspeedtest
      # - traefik.http.services.openspeedtest.loadbalancer.server.port=3000
      # - ↓ Route to Authentik outpost instead of the app directly
      - traefik.http.routers.openspeedtest.service=authentik-outpost@file
      # -  ↓ Apply security headers + rate limiting
      - traefik.http.routers.openspeedtest.middlewares=authentik-proxy-chain@file


networks:
  private:
    name: private
    internal: true
  proxy:
    name: proxy
    external: true
