---
name: arcane-agent
services:
  arcane-agent:
    image: ghcr.io/getarcaneapp/agent:v2.3.2
    container_name: arcane-agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      - /home/jackstockley/infrastructure/docker/racknerd:/app/data/projects
    environment:
      EDGE_AGENT: "true"
      EDGE_TRANSPORT: "poll"
      MANAGER_API_URL: "http://arcane-manager-photo-server.tail5bef84.ts.net"
      TZ: "America/Chicago"
    env_file:
      - .env
    network_mode: service:tailscale
    restart: unless-stopped

  tailscale:
    image: tailscale/tailscale:v1.98.8
    container_name: ts-agent-host
    volumes:
      - ts-state:/var/lib/tailscale
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_EXTRA_ARGS=--ssh=false
    env_file:
      - .env
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - NET_RAW
    hostname: arcane-agent-racknerd

volumes:
  ts-state:
