---
name: api
services:
  api:
    image: jnstockley/api:testing
    container_name: api
    env_file:
      - ./.env
    networks:
      - api
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:5000/health-check || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.entrypoints=websecure
      - traefik.http.routers.api.rule=Host(`api.jstockley.com`)
      - traefik.http.routers.api.tls=true
      - traefik.http.routers.api.tls.certresolver=production
      - traefik.http.routers.api.service=api
      - traefik.http.services.api.loadbalancer.server.port=5000
      - traefik.docker.network=api

networks:
  api:
    external: true
    name: api
    ipam:
      driver: default
      config:
        - subnet: 172.18.6.0/24
