---
name: api
services:
  api:
    image: jnstockley/api:v0.2.78
    container_name: api
    environment:
      - TZ=America/Chicago
      - PGTZ=America/Chicago
    env_file:
      - .env
    networks:
      - proxy
      - private
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.api.entrypoints=websecure
      - traefik.http.routers.api.rule=Host(`api.jstockley.com`)
      - traefik.http.routers.api.tls=true
      - traefik.http.routers.api.tls.certresolver=production
      - traefik.http.routers.api.service=api
      - traefik.http.services.api.loadbalancer.server.port=5000
    security_opt:
      - no-new-privileges:true

networks:
  proxy:
    name: proxy
    external: true
    enable_ipv4: true
    enable_ipv6: true
  private:
    name: private
    internal: true
    external: true
    enable_ipv4: true
    enable_ipv6: true
