---
name: api
services:
  api:
    image: jnstockley/api:testing
    container_name: api
    environment:
      - TZ=America/Chicago
    env_file:
      - .env
    networks:
      - api
      - postgres
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.entrypoints=websecure
      - traefik.http.routers.api.rule=Host(`api.jstockley.com`)
      - traefik.http.routers.api.tls=true
      - traefik.http.routers.api.tls.certresolver=production
      - traefik.http.routers.api.service=api
      - traefik.http.services.api.loadbalancer.server.port=5000
      - traefik.docker.network=api

networks:
  api:
    name: api
    external: true
  postgres:
    name: postgres
    external: true
