services:
  api:
    container_name: jnstockley-api
    image: jnstockley/api:v0.0.2-fix
    working_dir: "/opt/jstockley-api"
    env_file:
      - path: ./.env
        required: true
    restart: "unless-stopped"
    networks:
      - jnstockley-api

networks:
  jnstockley-api:
    external: true
    name: "jnstockley-api"