---
name: uptime-kuma
services:
  uptime-kuma:
    image: louislam/uptime-kuma:2.3.1-slim
    container_name: uptime-kuma
    volumes:
      - ./data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    networks:
      - proxy
    restart: unless-stopped
    healthcheck:
      test: node ./extra/healthcheck.js
      interval: 60s
      retries: 5
      start_period: 180s
      timeout: 30s
    labels:
      - traefik.enable=true
      - traefik.http.routers.uptime-kuma.entrypoints=websecure
      - traefik.http.routers.uptime-kuma.rule=Host(`status.local.jstockley.com`)
      - traefik.http.routers.uptime-kuma.tls=true
      - traefik.http.routers.uptime-kuma.tls.certresolver=production
      - traefik.http.routers.unifi-toolkit.service=authentik-outpost@file
      - traefik.http.routers.unifi-toolkit.middlewares=authentik-proxy-chain@file
    security_opt:
      - no-new-privileges:true

networks:
  private:
    name: private
    internal: true
    external: true
