---
name: redis
services:
  redis:
    image: redis:8.2.2-alpine
    container_name: redis
    volumes:
      - ./data/:/data
    environment:
      - TZ=America/Chicago
    networks:
      - private
    command: --save 60 1 --loglevel warning
    restart: unless-stopped
    healthcheck:
      test: redis-cli ping | grep PONG
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    security_opt:
      - no-new-privileges:true

networks:
  private:
    name: private
    external: true
