---
name: redis
services:
  redis:
    image: redis:8.0.0-alpine
    container_name: redis
    volumes:
      - ./data/:/data
    environment:
      - TZ=America/Chicago
    networks:
      - private
    command: --save 60 1 --loglevel warning
    restart: unless-stopped
    healthcheck:
      test: redis-cli ping | grep PONG
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    logging:
      driver: loki
      options:
        loki-url: "https://loki.local.jstockley.com/loki/api/v1/push"
        loki-retries: 2
        loki-max-backoff: 800ms
        loki-timeout: 1s
        keep-file: "true"
        mode: "non-blocking"
    deploy:
      resources:
        limits:
          memory: 256M
    security_opt:
      - no-new-privileges:true

networks:
  private:
    name: private
    external: true
