---
name: web-scrapper
services:
  web-scrapper-hyundai:
    image: jnstockley/web-scrapper:v0.3.110
    container_name: web_scrapper_hyundai
    volumes:
      - ./hyundai-data/:/web-scrapper/data/
    environment:
      - TZ=America/Chicago
      - SCRAPPER=diff
      - URL=https://update.hyundai.com/US/EN/updateNoticeList
      - PERCENTAGE=5
      - SLEEP_TIME_SEC=21600
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: poetry run python3 src/healthcheck.py
      interval: 60s
      retries: 3
      start_period: 20s
      timeout: 10s
    logging:
      driver: loki
      options:
        loki-url: "https://loki.local.jstockley.com/loki/api/v1/push"
        loki-retries: 2
        loki-max-backoff: 800ms
        loki-timeout: 1s
        keep-file: "true"
        mode: "non-blocking"
    deploy:
      resources:
        limits:
          memory: 256M
    security_opt:
      - no-new-privileges:true
