services:
  renovate-ce:
    container_name: mend_renovate
    image: ghcr.io/mend/renovate-ce:8.6.0-full
    labels:
      - traefik.enable=true
      - traefik.http.routers.mend.entrypoints=websecure
      - traefik.http.routers.mend.rule=Host(`mend.jstockley.com`)
      - traefik.http.routers.mend.tls=true
      - traefik.http.routers.mend.tls.certresolver=production
      - traefik.http.routers.mend.service=mend
      - traefik.http.services.mend.loadbalancer.server.port=8080
      - traefik.docker.network=mend
    volumes:
      - ./logs:/logs
      - ./certs:/certs
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8080/health" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 100s
    env_file:
      - .env
    networks:
      - mend
      - postgres
    restart: unless-stopped

networks:
  mend:
    name: mend
    external: true
  postgres:
    name: postgres
    external: true