services:
  renovate-ce:
    # Check latest version here: https://github.com/mend/renovate-ce-ee/pkgs/container/renovate-ce
    image: ghcr.io/mend/renovate-ce:8.4.0-full
    labels:
      - traefik.enable=true
      - traefik.http.routers.mend.entrypoints=websecure
      - traefik.http.routers.mend.rule=Host(`mend.jstockley.com`)
      - traefik.http.routers.mend.tls=true
      - traefik.http.routers.mend.tls.certresolver=production
      - traefik.http.routers.mend.service=mend
      - traefik.http.services.mend.loadbalancer.server.port=8080
      - traefik.docker.network=mend
    volumes:
      - ./logs:/logs
      - ./certs:/certs
    env_file:
      - .env
    networks:
      - postgres-internal
      - mend

networks:
  postgres-internal:
    external: true
    name: postgres-internal
  mend:
    external: true
    name: mend
