---
name: immich
services:
  database:
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    container_name: immich_postgres
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    networks:
      - immich_private
    command:
      [
        "postgres",
        "-c",
        "shared_preload_libraries=vectors.so",
        "-c",
        'search_path="$$user", public, vectors',
        "-c",
        "logging_collector=on",
        "-c",
        "max_wal_size=2GB",
        "-c",
        "shared_buffers=512MB",
        "-c",
        "wal_compression=on"
      ]
    restart: unless-stopped
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' ||
        exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}'
        --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT
        COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo
        "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 100s
    deploy:
      resources:
        limits:
          memory: 256M
    security_opt:
      - no-new-privileges:true

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:v1.125.1
    container_name: immich_machine_learning
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    networks:
      - immich_private
    restart: unless-stopped
    healthcheck:
      test: python3 healthcheck.py
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 100s
    deploy:
      resources:
        limits:
          memory: 512M
    security_opt:
      - no-new-privileges:true

  immich-server:
    image: ghcr.io/immich-app/immich-server:v1.125.2
    container_name: immich_server
    depends_on:
      - database
      - redis
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ./healthcheck.js:/healthcheck/healthcheck.js
    env_file:
      - .env
    ports:
      - '0.0.0.0:2283:2283'
    networks:
      - immich
      - immich_private
    restart: unless-stopped
    healthcheck:
      test: immich-healthcheck
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 100s
    labels:
      - traefik.enable=true
      - traefik.http.routers.photos.entrypoints=websecure
      - traefik.http.routers.photos.rule=Host(`photos.jstockley.com`)
      - traefik.http.routers.photos.tls=true
      - traefik.http.routers.photos.tls.certresolver=production
      - traefik.http.routers.photos.service=photos
      - traefik.http.services.photos.loadbalancer.server.port=2283
      - traefik.docker.network=immich
    deploy:
      resources:
        limits:
          memory: 1G
    security_opt:
      - no-new-privileges:true

  redis:
    image: docker.io/redis:6.2-alpine@sha256:905c4ee67b8e0aa955331960d2aa745781e6bd89afc44a8584bfd13bc890f0ae
    container_name: immich_redis
    networks:
      - immich_private
    restart: unless-stopped
    healthcheck:
      test: redis-cli ping || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 100s
    deploy:
      resources:
        limits:
          memory: 256M

    security_opt:
      - no-new-privileges:true

networks:
  immich:
    name: immich
    external: true
  immich_private:
    name: immich_private
    external: true

volumes:
  model-cache:
