---
name: immich
services:
  database:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
    container_name: immich_postgres
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    networks:
      - private
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE_NAME}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    security_opt:
      - no-new-privileges:true

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:v1.143.1
    container_name: immich_machine_learning
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    networks:
      - private
    restart: unless-stopped
    healthcheck:
      test: python3 healthcheck.py
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 100s
    deploy:
      resources:
        limits:
          memory: 512M
    security_opt:
      - no-new-privileges:true

  immich-server:
    image: ghcr.io/immich-app/immich-server:v1.143.1
    container_name: immich_server
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ./healthcheck.js:/healthcheck/healthcheck.js
    env_file:
      - .env
    networks:
      - proxy
      - private
    restart: unless-stopped
    healthcheck:
      test: immich-healthcheck
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 100s
    labels:
      - traefik.enable=true
      - traefik.http.routers.photos.entrypoints=websecure
      - traefik.http.routers.photos.rule=Host(`photos.jstockley.com`) || Host(`photos.local.jstockley.com`)
      - traefik.http.routers.photos.tls=true
      - traefik.http.routers.photos.tls.certresolver=production
      - traefik.http.routers.photos.service=photos
      - traefik.http.services.photos.loadbalancer.server.port=2283
    deploy:
      resources:
        limits:
          memory: 1G
    security_opt:
      - no-new-privileges:true

networks:
  proxy:
    name: proxy
    external: true
  private:
    name: private
    internal: true
    external: true

volumes:
  model-cache:
