# dclint disable no-duplicate-exported-ports
---
name: adguard
services:
  adguard:
    image: adguard/adguardhome:v0.107.55
    container_name: adguard
    volumes:
      - ./conf:/opt/adguardhome/conf
      - ./work:/opt/adguardhome/work
    environment:
      - TZ=America/Chicago
    ports:
      - '0.0.0.0:53:53/tcp'
      - '0.0.0.0:53:53/udp'
    networks:
      - adguard
    restart: unless-stopped
    healthcheck:
      test: wget -nv -t 1 --spider --no-check-certificate https://localhost
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    labels:
      - traefik.enable=true
      - traefik.http.routers.adguard.entrypoints=web
      - traefik.http.routers.adguard.rule=Host(`dns.jstockley.com`)
      - raefik.http.middlewares.adguard-https-redirect.redirectscheme.scheme=http
      - raefik.http.routers.adguard.middlewares=adguard-https-redirec
      - traefik.http.routers.adguard-secure.entrypoints=websecure
      - traefik.http.routers.adguard-secure.rule=Host(`dns.jstockley.com`)
      - traefik.http.routers.adguard-secure.tls=true
      - traefik.http.routers.adguard-secure.tls.certresolver=production
      - traefik.http.routers.adguard-secure.service=adguard-secure
      - traefik.http.services.adguard-secure.loadbalancer.server.port=80
      - traefik.docker.network=adguard
    cap_add:
      - NET_ADMIN
    cap_drop:
      - ALL
    expose:
      - '53'
    security_opt:
      - no-new-privileges:true

networks:
  adguard:
    name: adguard
    external: true
