# dclint disable no-duplicate-exported-ports
---
name: adguard
services:
  adguard:
    image: adguard/adguardhome:v0.107.59
    container_name: adguard
    volumes:
      - ./conf:/opt/adguardhome/conf
      - ./work:/opt/adguardhome/work
    environment:
      - TZ=America/Chicago
    ports:
      - '0.0.0.0:53:53/tcp'
      - '0.0.0.0:53:53/udp'
    networks:
      - proxy
    restart: unless-stopped
    healthcheck:
      test: wget -nv -t 1 --spider --no-check-certificate https://localhost
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    logging:
      driver: loki
      options:
        loki-url: "https://loki.local.jstockley.com/loki/api/v1/push"
        loki-retries: 2
        loki-max-backoff: 800ms
        loki-timeout: 1s
        keep-file: "true"
        mode: "non-blocking"
    labels:
      - traefik.enable=true
      - traefik.http.routers.adguard.entrypoints=web
      - traefik.http.routers.adguard.rule=Host(`dns.jstockley.com`)
      - traefik.http.middlewares.adguard-https-redirect.redirectscheme.scheme=http
      - traefik.http.routers.adguard.middlewares=adguard-https-redirect
      - traefik.http.routers.adguard-secure.entrypoints=websecure
      - traefik.http.routers.adguard-secure.rule=Host(`dns.jstockley.com`)
      - traefik.http.routers.adguard-secure.tls=true
      - traefik.http.routers.adguard-secure.tls.certresolver=production
      - traefik.http.routers.adguard-secure.service=adguard-secure
      - traefik.http.services.adguard-secure.loadbalancer.server.port=80
    cap_add:
      - NET_ADMIN
    deploy:
      resources:
        limits:
          memory: 1G
    expose:
      - '53'
    security_opt:
      - no-new-privileges:true

networks:
  proxy:
    name: proxy
    external: true
