version: "3.6"

services:
  cloudflare-ddns:
    container_name: "cloudflare-ddns"
    image: "timothyjmiller/cloudflare-ddns:latest"
    networks:
      - "cloudflare-ddns"
    restart: "unless-stopped"
    volumes:
      - "/home/jackstockley/infrastructure/docker/racknerd/cloudflare-ddns/config.json:/config.json"

networks:
  cloudflare-ddns:
    external: true
    name: "cloudflare-ddns"
