services:
  server:
    image: gitea/gitea:1.21.11
    container_name: gitea
    restart: always
    environment:
      - TZ=America/Chicago
    env_file:
      - ./.env
    volumes:
      - ./data:/data
    networks:
      - gitea
    labels:
      - traefik.enable=true
      - traefik.http.routers.gitea.entrypoints=websecure
      - traefik.http.routers.gitea.rule=Host(`git.jstockley.com`)
      - traefik.http.routers.gitea.tls=true
      - traefik.http.routers.gitea.tls.certresolver=production
      - traefik.http.routers.gitea.service=gitea
      - traefik.http.services.gitea.loadbalancer.server.port=3000
      - traefik.docker.network=gitea

networks:
  gitea:
    external: true
    name: gitea
    ipam:
      driver: default
      config:
        - subnet: 172.18.9.0/24