---
name: beszel
services:
  beszel:
    image: henrygd/beszel:0.14.1
    container_name: beszel
    volumes:
      - ./data:/beszel_data
    networks:
      - proxy
      - beszel-agent
    restart: unless-stopped
    healthcheck:
      test: ['CMD', '/beszel', 'health', '--url', 'http://localhost:8090']
      start_period: 5s
      interval: 120s
      timeout: 10s
      retries: 5
    # labels:
    #   - traefik.enable=true
    #   - traefik.http.routers.beszel.entrypoints=websecure
    #   - traefik.http.routers.beszel.rule=Host(`stats.local.jstockley.com`)
    #   - traefik.http.routers.beszel.tls=true
    #   - traefik.http.routers.beszel.tls.certresolver=production
    #   - traefik.http.routers.beszel.service=beszel
    #   - traefik.http.services.beszel.loadbalancer.server.port=8090
    security_opt:
      - no-new-privileges:true

  beszel-agent:
    image: henrygd/beszel-agent:0.13.2
    container_name: beszel-agent-photo-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/photos/.beszel:/extra-filesystems/sdb1:ro
    env_file:
      - .env
    networks:
      - beszel-agent
    restart: unless-stopped
    healthcheck:
      test: ['CMD', '/agent', 'health']
      start_period: 5s
      interval: 120s
      timeout: 10s
      retries: 5
    security_opt:
      - no-new-privileges:true

networks:
  proxy:
    name: proxy
    external: true
  beszel-agent:
    name: beszel-agent
