---
name: beszel
services:
  beszel:
    image: henrygd/beszel:0.9.1
    container_name: beszel
    volumes:
      - ./data:/beszel_data
    network_mode: service:wireguard-beszel
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.beszel.entrypoints=websecure
      - traefik.http.routers.beszel.rule=Host(`stats.local.jstockley.com`)
      - traefik.http.routers.beszel.tls=true
      - traefik.http.routers.beszel.tls.certresolver=production
      - traefik.http.routers.beszel.service=beszel
      - traefik.http.services.beszel.loadbalancer.server.port=8090
      - traefik.docker.network=beszel
    security_opt:
      - no-new-privileges:true

  beszel-agent:
    image: henrygd/beszel-agent:0.9.1
    container_name: beszel-agent-photo-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/photos/.beszel:/extra-filesystems/sdb1:ro
    env_file:
      - .env
    networks:
      - beszel-agent
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

  wireguard-beszel:
    image: linuxserver/wireguard:1.0.20210914@sha256:84c9fef8070216cf2c834e90af62e4a45226aa64e9fb0a3d3b9d13bceaaf8f34
    container_name: wireguard-beszel
    volumes:
      - ./config:/config/wg_confs
      - /lib/modules:/lib/modules
    env_file:
      - .env
    networks:
      - beszel
      - beszel-agent
    restart: unless-stopped
    healthcheck:
      test: curl --fail https://google.com || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 100s
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    deploy:
      resources:
        limits:
          memory: 256M
    security_opt:
      - no-new-privileges:true
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1

networks:
  beszel:
    name: beszel
    external: true
  beszel-agent:
    name: beszel-agent
