name: WireGuard test

on:
  workflow_dispatch:

jobs:
  wireguard_example:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt-get update
          sudo apt-get install -y wireguard resolvconf
          echo "${{ secrets.IOWA_HOME_VPN_CONF }}" > vpn.conf
          sudo chmod 600 vpn.conf
          sudo wg-quick up ./vpn.conf

      - run: |
          curl -4 icanhazip.com
          ping -c5 192.168.0.1
          ping -c5 photo-server.local.jstockley.com
