---
name: authentik
services:
  server:
    image: ghcr.io/goauthentik/server:2024.10.4
    container_name: authentik
    volumes:
      - ./media:/media
      - ./custom-templates:/templates
    environment:
      - TZ=America/Chicago
    env_file:
      - .env
    networks:
      - authentik
      - authentik-private
      - redis
      - postgres
      - wireguard
    command: server
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.auth.entrypoints=websecure
      - traefik.http.routers.auth.rule=Host(`auth.jstockley.com`)
      - traefik.http.routers.auth.tls=true
      - traefik.http.routers.auth.tls.certresolver=production
      - traefik.http.routers.auth.service=auth
      - traefik.http.services.auth.loadbalancer.server.port=9000
      - traefik.docker.network=authentik
  worker:
    image: ghcr.io/goauthentik/server:2024.10.4
    container_name: authentik_worker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./media:/media
      - ./certs:/certs
      - ./custom-templates:/templates
    environment:
      - TZ=America/Chicago
    env_file:
      - .env
    networks:
      - authentik-private
      - redis
      - postgres
      - wireguard
    command: worker
    restart: unless-stopped
    user: root

networks:
  authentik:
    external: true
    name: authentik
  authentik-private:
    external: true
    name: authentik-private
  postgres:
    name: postgres
    external: true
  redis:
    name: redis
    external: true
  wireguard:
    name: wireguard
    external: true
