services:
  server:
    image: ghcr.io/goauthentik/server:2024.6.0
    container_name: authentik
    restart: unless-stopped
    command: server
    volumes:
      - ./media:/media
      - ./custom-templates:/templates
    env_file:
      - .env
    environment:
      - TZ=America/Chicago
    networks:
      - authentik
      - authentik-private
      - redis
      - postgres-internal
    labels:
      - traefik.enable=true
      - traefik.http.routers.auth.entrypoints=websecure
      - traefik.http.routers.auth.rule=Host(`auth.jstockley.com`)
      - traefik.http.routers.auth.tls=true
      - traefik.http.routers.auth.tls.certresolver=production
      - traefik.http.routers.auth.service=auth
      - traefik.http.services.auth.loadbalancer.server.port=9000
      - traefik.docker.network=authentik
  worker:
    image: ghcr.io/goauthentik/server:2024.6.0
    container_name: authentik_worker
    restart: unless-stopped
    command: worker
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./media:/media
      - ./certs:/certs
      - ./custom-templates:/templates
    env_file:
      - .env
    environment:
      - TZ=America/Chicago
    networks:
      - authentik-private
      - redis
      - postgres-internal

volumes:
  database:
    driver: local
  redis:
    driver: local

networks:
  authentik-private:
    external: true
    name: authentik-private
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/24
  authentik:
    external: true
    name: authentik
    ipam:
      driver: default
      config:
        - subnet: 172.18.10.0/24
  postgres-internal:
    external: true
    name: postgres-internal
    ipam:
      driver: default
      config:
        - subnet: 172.19.1.0/24
  redis:
    external: true
    name: redis
    ipam:
      driver: default
      config:
        - subnet: 172.19.2.0/24
