services:
  traefik:
    image: traefik:v3.1.6
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./config/conf/:/etc/traefik/conf/
      - ./config/certs/:/etc/traefik/certs/
      - ./logs/:/var/log/traefik/
    networks:
      immich:
      gitea:
      mc:
      airflow:
      postgres-external:
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.entrypoints=web
      - traefik.http.routers.traefik.rule=Host(`traefik.local.jstockley.com`)
      - traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https
      - traefik.http.routers.traefik.middlewares=traefik-https-redirect
      - traefik.http.routers.traefik-secure.entrypoints=websecure
      - traefik.http.routers.traefik-secure.rule=Host(`traefik.local.jstockley.com`)
      - traefik.http.routers.traefik-secure.tls=true
      - traefik.http.routers.traefik-secure.tls.certresolver=production
      - traefik.http.routers.traefik-secure.tls.domains[0].main=local.jstockley.com
      - traefik.http.routers.traefik-secure.tls.domains[0].sans=*.local.jstockley.com
      - traefik.http.routers.traefik-secure.service=api@internal
    healthcheck:
      test:
        - CMD
        - traefik
        - healthcheck
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

networks:
  immich:
    external: true
  gitea:
    external: true
    name: gitea
  mc:
    external: true
  airflow:
    external: true
  postgres-external:
    external: true