---
name: traefik
services:
  traefik:
    image: traefik:v3.3.6
    container_name: traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./config/conf/:/etc/traefik/conf/
      - ./config/certs/:/etc/traefik/certs/
      - traefik-logs:/var/log/traefik/
    env_file:
      - .env
    ports:
      - '0.0.0.0:80:80'
      - '0.0.0.0:443:443'
      - '0.0.0.0:25565:25565/tcp'
    networks:
      - proxy
      - private
      - nextcloud
      - bitwarden
    restart: unless-stopped
    healthcheck:
      test: traefik healthcheck
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    logging:
      driver: loki
      options:
        loki-url: "https://loki.local.jstockley.com/loki/api/v1/push"
        loki-retries: 2
        loki-max-backoff: 800ms
        loki-timeout: 1s
        keep-file: "true"
        mode: "non-blocking"
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.entrypoints=web
      - traefik.http.routers.traefik.rule=Host(`traefik.local.jstockley.com`)
      - traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https
      - traefik.http.routers.traefik.middlewares=traefik-https-redirect
      - traefik.http.routers.traefik-secure.entrypoints=websecure
      - traefik.http.routers.traefik-secure.rule=Host(`traefik.local.jstockley.com`)
      - traefik.http.routers.traefik-secure.tls=true
      - traefik.http.routers.traefik-secure.tls.certresolver=production
      - traefik.http.routers.traefik-secure.tls.domains[0].main=local.jstockley.com
      - traefik.http.routers.traefik-secure.tls.domains[0].sans=*.local.jstockley.com
      - traefik.http.routers.traefik-secure.service=api@internal
    deploy:
      resources:
        limits:
          memory: 512M
    security_opt:
      - no-new-privileges:true

networks:
  proxy:
    name: proxy
    external: true
  private:
    name: private
    internal: true
    external: true
  nextcloud:
    name: nextcloud
    external: true
  bitwarden:
    name: bitwarden
    external: true

volumes:
  traefik-logs:
