---
services:
  traefik:
    image: traefik:v3.2.1
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
      - "25565:25565/tcp"
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./config/conf/:/etc/traefik/conf/
      - ./config/certs/:/etc/traefik/certs/
      - ./logs/:/var/log/traefik/
    networks:
      - airflow
      - gitea
      - immich
      - mend
      - minecraft
      - pgadmin
      - syncthing
      - uptime-kuma
      - wireguard
      - loki
      - graynet
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.entrypoints=web
      - traefik.http.routers.traefik.rule=Host(`traefik.local.jstockley.com`)
      - traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https
      - traefik.http.routers.traefik.middlewares=traefik-https-redirect
      - traefik.http.routers.traefik-secure.entrypoints=websecure
      - traefik.http.routers.traefik-secure.rule=Host(`traefik.local.jstockley.com`)
      - traefik.http.routers.traefik-secure.tls=true
      - traefik.http.routers.traefik-secure.tls.certresolver=production
      - traefik.http.routers.traefik-secure.tls.domains[0].main=local.jstockley.com
      - traefik.http.routers.traefik-secure.tls.domains[0].sans=*.local.jstockley.com
      - traefik.http.routers.traefik-secure.service=api@internal
    healthcheck:
      test: traefik healthcheck
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

networks:
  airflow:
    name: airflow
    external: true
  gitea:
    name: gitea
    external: true
  immich:
    name: immich
    external: true
  mend:
    name: mend
    external: true
  minecraft:
    name: minecraft
    external: true
  pgadmin:
    name: pgadmin
    external: true
  syncthing:
    name: syncthing
    external: true
  uptime-kuma:
    name: uptime-kuma
    external: true
  wireguard:
    name: wireguard
    external: true
  loki:
    name: loki
    external: true
  graynet:
    name: graynet
    external: true


