---
name: bluesky
services:
  bluesky:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bluesky
    environment:
      - TZ=America/Chicago
    #env_file:
    #  - .env
    ports:
      - '8080:80'
    networks:
      - bluesky
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.bluesky.entrypoints=websecure
      - traefik.http.routers.bluesky.rule=Host(`bluesky.jstockley.com`)
      - traefik.http.routers.bluesky.tls=true
      - traefik.http.routers.bluesky.tls.certresolver=production
      - traefik.http.routers.bluesky.service=bluesky
      - traefik.http.services.bluesky.loadbalancer.server.port=3000
      - traefik.docker.network=bluesky

networks:
  bluesky:
    name: bluesky
    external: true
