---
name: bluesky
services:
  pds:
    image: ghcr.io/bluesky-social/pds:0.4.74
    container_name: pds
    volumes:
      - type: bind
        source: pds
        target: /pds
    env_file:
      - .env
    networks:
      - bluesky
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.bluesky.entrypoints=websecure
      - traefik.http.routers.bluesky.rule=Host(`bluesky.jstockley.com`)
      - traefik.http.routers.bluesky.tls=true
      - traefik.http.routers.bluesky.tls.certresolver=production
      - traefik.http.routers.bluesky.service=bluesky
      - traefik.http.services.bluesky.loadbalancer.server.port=2583
      - traefik.docker.network=bluesky

networks:
  bluesky:
    name: bluesky
    external: true
