---
name: authentik
services:
  proxy:
    image: ghcr.io/goauthentik/proxy:2026.2.1
    container_name: authentik_proxy
    environment:
      AUTHENTIK_HOST: http://authentik:9000
      AUTHENTIK_INSECURE: "false"
      AUTHENTIK_HOST_BROWSER: https://idp.jstockley.com
      # Starting with 2021.9, you can optionally set this too
      # when authentik_host for internal communication doesn't match the public URL
      # AUTHENTIK_HOST_BROWSER: https://external-domain.tld
    env_file:
      - .env
    networks:
      - proxy
      - private
    labels:
      traefik.enable: true
      traefik.port: 9000
      traefik.http.routers.authentik.rule: Host(`app.company`) && PathPrefix(`/outpost.goauthentik.io/`)
      # `authentik-proxy` refers to the service name in the compose file.
      traefik.http.middlewares.authentik.forwardauth.address: http://authentik-proxy:9000/outpost.goauthentik.io/auth/traefik
      traefik.http.middlewares.authentik.forwardauth.trustForwardHeader: true
      traefik.http.middlewares.authentik.forwardauth.authResponseHeaders: X-authentik-username,X-authentik-groups,X-authentik-entitlements,X-authentik-email,X-authentik-name,X-authentik-uid,X-authentik-jwt,X-authentik-meta-jwks,X-authentik-meta-outpost,X-authentik-meta-provider,X-authentik-meta-app,X-authentik-meta-version
    restart: unless-stopped


  server:
    image: ghcr.io/goauthentik/server:2026.2.1
    container_name: authentik
    volumes:
      - ./media:/media
      - ./custom-templates:/templates
    environment:
      - TZ=America/Chicago
    env_file:
      - .env
    networks:
      - proxy
      - private
    command: server
    restart: unless-stopped
    healthcheck:
      test: ak healthcheck
      interval: 60s
      retries: 5
      start_period: 180s
      timeout: 30s
    labels:
      - traefik.enable=true
      - traefik.http.routers.auth.entrypoints=websecure
      - traefik.http.routers.auth.rule=Host(`idp.jstockley.com`)
      - traefik.http.routers.auth.tls=true
      - traefik.http.routers.auth.tls.certresolver=production
      - traefik.http.routers.auth.service=auth
      - traefik.http.services.auth.loadbalancer.server.port=9000
    security_opt:
      - no-new-privileges:true

  worker:
    image: ghcr.io/goauthentik/server:2026.2.1
    container_name: authentik_worker
    volumes:
      - ./media:/media
      - ./certs:/certs
      - ./custom-templates:/templates
    environment:
      - TZ=America/Chicago
    env_file:
      - .env
    networks:
      - private
    command: worker
    restart: unless-stopped
    healthcheck:
      test: ak healthcheck
      interval: 60s
      retries: 5
      start_period: 180s
      timeout: 30s
    user: root
    security_opt:
      - no-new-privileges:true

networks:
  proxy:
    external: true
    name: proxy
  private:
    name: private
    internal: true
    external: true
