---
name: authentik
services:
  server:
    image: ghcr.io/goauthentik/server:2025.6.0
    container_name: authentik
    volumes:
      - ./media:/media
      - ./custom-templates:/templates
    environment:
      - TZ=America/Chicago
    env_file:
      - .env
    networks:
      - proxy
      - private
    command: server
    restart: unless-stopped
    healthcheck:
      test: ak healthcheck
      interval: 60s
      retries: 5
      start_period: 180s
      timeout: 30s
    logging:
      driver: loki
      options:
        loki-url: "https://loki.local.jstockley.com/loki/api/v1/push"
        loki-retries: 2
        loki-max-backoff: 800ms
        loki-timeout: 1s
        keep-file: "true"
        mode: "non-blocking"
    labels:
      - traefik.enable=true
      - traefik.http.routers.auth.entrypoints=websecure
      - traefik.http.routers.auth.rule=Host(`idp.jstockley.com`)
      - traefik.http.routers.auth.tls=true
      - traefik.http.routers.auth.tls.certresolver=production
      - traefik.http.routers.auth.service=auth
      - traefik.http.services.auth.loadbalancer.server.port=9000
    deploy:
      resources:
        limits:
          memory: 512M
    security_opt:
      - no-new-privileges:true

  worker:
    image: ghcr.io/goauthentik/server:2025.6.0
    container_name: authentik_worker
    volumes:
      - ./media:/media
      - ./certs:/certs
      - ./custom-templates:/templates
    environment:
      - TZ=America/Chicago
    env_file:
      - .env
    networks:
      - private
    command: worker
    restart: unless-stopped
    healthcheck:
      test: ak healthcheck
      interval: 60s
      retries: 5
      start_period: 180s
      timeout: 30s
    logging:
      driver: loki
      options:
        loki-url: "https://loki.local.jstockley.com/loki/api/v1/push"
        loki-retries: 2
        loki-max-backoff: 800ms
        loki-timeout: 1s
        keep-file: "true"
        mode: "non-blocking"
    user: root
    deploy:
      resources:
        limits:
          memory: 256M
    security_opt:
      - no-new-privileges:true

networks:
  proxy:
    external: true
    name: proxy
  private:
    name: private
    internal: true
    external: true
