---
name: promtail
services:
  promtail:
    image: grafana/promtail:3.5.3
    container_name: promtail
    volumes:
      - ./config/config.yml:/mnt/config/config.yml:ro
      - /var/log:/var/log:ro
      - ../traefik/logs/:/traefik:ro
    command: "-config.file=/mnt/config/config.yml"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
