services:
  app:
    image: "jc21/nginx-proxy-manager:2.11.1"
    container_name: "nginx-proxy-manager"
    restart: "unless-stopped"
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    volumes:
      - "./data:/data"
      - "./letsencrypt:/etc/letsencrypt"
    networks:
      - "portainer"
      - "adguard"
      - "uptime-kuma"
      - "vaultwarden"
      - "dockge"
      - "jnstockley-api"
      - "postgres-external"
      - "nginx-proxy-manager"

networks:
  portainer:
    external: true
    name: "portainer"
  adguard:
    external: true
    name: "adguard"
  uptime-kuma:
    external: true
    name: "uptime-kuma"
  vaultwarden:
    external: true
    name: "vaultwarden"
  dockge:
    name: "dockge"
    external: true
  jnstockley-api:
    external: true
    name: "jnstockley-api"
  postgres-external:
    external: true
    name: "postgres-external"
  nginx-proxy-manager:
    external: true
    name: "nginx-proxy-manager"
