name: Restart AdGuard

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'

jobs:
  adguard_restart:
    name: Restart AgGuard Container
    runs-on: ubuntu-latest

    steps:
      - name: Restart AdGuard Container
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.RACKNERD_IP }}
          username: jackstockley
          key: ${{ secrets.RACKNERD_SSH_KEY }}
          passphrase: ${{ secrets.RACKNERD_SSH_PASSWORD }}
          script: docker compose -f ~/infrastructure/docker/racknerd/adguard/compose.yml up -d --force-recreate --remove-orphans