name: Backups

on:  
  workflow_dispatch:

jobs:
  backup:
    name: Backup Status
    runs-on: ubuntu-latest
    
    steps:
      - name: Step 1 - Checkout
        uses: actions/checkout@v3
      - name: Step 2 - Setup and Connect to Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:github
      - name: Step 3 - Create config file
        run: |
          mkdir resources
          touch resources/config.toml
          echo "\"${{ secrets.BACKUP_SERVER }}\" = \"${{ secrets.BACKUP_SERVER_API_KEY }}\"" >> resources/config.toml
          echo "\"${{ secrets.CHICAGO_HOME }}\" = \"${{ secrets.CHICAGO_HOME_API_KEY }}\"" >> resources/config.toml
          echo "\"${{ secrets.IOWA_HOME }}\" = \"${{ secrets.IOWA_HOME_API_KEY }}\"" >> resources/config.toml
          echo "\"${{ secrets.SYNOLOGY }}\" = \"${{ secrets.SYNOLOGY_API_KEY }}\"" >> resources/config.toml
          echo "\"${{ secrets.RACKNERD }}\" = \"${{ secrets.RACKNERD_API_KEY }}\"" >> resources/config.toml
      - name: Step 4 - Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' 
      - name: Step 5 - Install Poetry and Dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install --no-root
      - name: Step 6 - Run Tests
        run: poetry run pytest tests/*.py
