---
name: Backups

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  backup:
    name: Backup Status
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Checkout
        uses: actions/checkout@v4
      - name: Step 2 - Set Timezone
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "America/Chicago"

      - name: Step 2 - WireGuard Connection
        run: |
          sudo apt-get update
          sudo apt-get install -y wireguard resolvconf
          echo "${{ secrets.IOWA_HOME_VPN_CONF }}" > wg0.conf
          echo "${{ secrets.CHICAGO_HOME_VPN_CONF }}" > wg1.conf
          sudo chmod 600 wg0.conf
          sudo chmod 600 wg1.conf
          sudo cp wg0.conf /etc/wireguard/
          sudo cp wg1.conf /etc/wireguard/
          sudo wg-quick up wg0
          sudo wg-quick up wg1

      - name: Step 4 - Create config file
        run: |
          mkdir resources
          touch resources/config.toml
          echo "[Backups]"  >> resources/config.toml
          echo "[Backups.Iowa-Home]"  >> resources/config.toml
          echo "url = '${{ secrets.IOWA_HOME }}'"  >> resources/config.toml
          echo "api_key = '${{ secrets.IOWA_HOME_API_KEY }}'"  >> resources/config.toml
          echo "outdated_interval = 6" >> resources/config.toml
          echo "[Backups.Chicago-Home]"  >> resources/config.toml
          echo "url = '${{ secrets.CHICAGO_HOME }}'"  >> resources/config.toml
          echo "api_key = '${{ secrets.CHICAGO_HOME_API_KEY }}'"  >> resources/config.toml
          echo "outdated_interval = 6" >> resources/config.toml
          echo "[Backups.Photo-Server]"  >> resources/config.toml
          echo "url = '${{ secrets.PHOTO_SERVER }}'"  >> resources/config.toml
          echo "api_key = '${{ secrets.PHOTO_SERVER_API_KEY }}'"  >> resources/config.toml
          echo "outdated_interval = 6" >> resources/config.toml
          echo "[Backups.Racknerd]"  >> resources/config.toml
          echo "url = '${{ secrets.RACKNERD }}'"  >> resources/config.toml
          echo "api_key = '${{ secrets.RACKNERD_API_KEY }}'"  >> resources/config.toml
          echo "outdated_interval = 6" >> resources/config.toml
          echo "[Backups.Synology]"  >> resources/config.toml
          echo "url = '${{ secrets.SYNOLOGY }}'"  >> resources/config.toml
          echo "api_key = '${{ secrets.SYNOLOGY_API_KEY }}'"  >> resources/config.toml
          echo "outdated_interval = 6" >> resources/config.toml
          echo "[Backups.Backup-Server]"  >> resources/config.toml
          echo "url = '${{ secrets.BACKUP_SERVER }}'"  >> resources/config.toml
          echo "api_key = '${{ secrets.BACKUP_SERVER_API_KEY }}'"  >> resources/config.toml
          echo "outdated_interval = 6" >> resources/config.toml
      - name: Step 5 - Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          check-latest: true

      - name: Step 6 - Install Poetry and Dependencies
        run: |
          pip3 install -r requirements.txt
          poetry install --no-root --only main
      - name: Step 7 - Run Tests
        run: poetry run pytest tests/test_backups.py
