name: Backups

on:  
  workflow_dispatch:

jobs:
  backup:
    name: Backup Status
    runs-on: ubuntu-latest
    
    steps:
      - name: Step 1 - Checkout Nightly Branch
        uses: actions/checkout@v3
      - name: Step 2 - Setup and Connect to Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:github
      - name: Step 3 - Test Tailscale
        run: |
          ping ${{ secrets.BACKUP_SERVER_IP }} -c 5
          ping ${{ secrets.CHICAGO_HOME_IP }} -c 5
          ping ${{ secrets.IOWA_HOME_IP }} -c 5
          ping ${{ secrets.SYNOLOGY_IP }} -c 5
