name: Cloudflare

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  backup:
    name: Cloudflare Status
    runs-on: ubuntu-latest
    
    steps:
      - name: Step 1 - Checkout
        uses: actions/checkout@v4
      - name: Step 2 - Set Timezone
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "America/Chicago"
      - name: Step 3 - Create config file
        run: |
          mkdir resources
          touch resources/config.toml
          echo "[Cloudflare]"  >> resources/config.toml
          echo "api_key = '${{ secrets.CLOUDFLARE_API_KEY }}'"  >> resources/config.toml
          echo "zone_name = '${{ secrets.CLOUDFLARE_ZONE_NAME }}'" >> resources/config.toml
          echo "dns_records = ${{ secrets.CLOUDFLARE_DNS_RECORDS }}" >> resources/config.toml
          echo "applications = ${{ secrets.CLOUDFLARE_APP_NAMES }}" >> resources/config.toml
          echo "application-urls = ${{ secrets.CLOUDFLARE_APP_URLS }}" >> resources/config.toml
      - name: Step 4 - Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' 
      - name: Step 5 - Install Poetry and Dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install --no-root
      - name: Step 6 - Run Tests
        run: poetry run pytest tests/test_cloudflare.py
