name: Cloudflare Speedtest

on:
  #schedule:
  #  - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  backup:
    name: Speedtest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 21
      - name: create javascript file
        run: |
          touch speedtest.js
          echo "async function run() {" >> speedtest.js
          echo "    const {default: Speedtest } = await import('@cloudflare/speedtest');" >> speedtest.js
          echo "    new Speedtest().onFinish = results => console.log(results.getSummary());" >> speedtest.js
          echo "}" >> speedtest.js
          echo "run()" >> speedtest.js
      - name: install speedtest
        run: npm i @cloudflare/speedtest
      - name: run speedtest
        run: node speedtest.js
