name: Docker Compatibility

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - beta
    paths:
      - docker/racknerd/**

jobs:
  deploy:
    name: Test Docker Images compatibility
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Checkout code
        uses: actions/checkout@v4
      - name: Step 2 - Get Changes files
        id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'csv'
      - name: Step 3 - Create Config file
        run: |
          echo "${mapfile -d ',' -t added_modified_files < <(printf '%s,' '${{ steps.files.outputs.added_modified }}')}"
          #mkdir resources
          #touch resources/config.toml
          #echo "[Docker]"  >> resources/config.toml
          #echo "filed = '${{ secrets.CLOUDFLARE_API_KEY }}'"  >> resources/config.toml
          #echo "${{ steps.files.outputs.added_modified }}"
          #mapfile -d ',' -t added_modified_files < <(printf '%s,' '${{ steps.files.outputs.added_modified }}')
          #for added_modified_file in "${added_modified_files[@]}"; do
          #  echo "Do something with this ${added_modified_file}."
          #done