name: Docker Compatibility

on:
  workflow_dispatch:
  pull_request:
    branches:
      - beta
    paths:
      - docker/racknerd/**

jobs:
  deploy:
    name: Test Docker Images compatibility
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Checkout code
        uses: actions/checkout@v4
      - name: Step 2 - Set Timezone
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "America/Chicago"
      - name: Step 3 - Get Changes files
        id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'csv'
      - name: Step 4 - Create Config file
        run: |
          mkdir resources
          touch resources/config.toml
          echo "[Docker]"  >> resources/config.toml
          echo "files = '${{ steps.files.outputs.added_modified }}'"  >> resources/config.toml
      - name: Step 5 - Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Step 6 - Install Poetry and Dependencies
        run: |
          pipx install poetry==1.8
          poetry install --no-root --with=docker
      - name: Step 7 - Run Tests
        run: poetry run pytest tests/test_containers.py