name: Docker Compatibility

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - beta
    paths:
      - docker/racknerd/**

jobs:
  deploy:
    name: Test Docker Images compatibility
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Checkout code
        uses: actions/checkout@v4
      - name: Step 2 - Get Changes files
        uses: jitterbit/get-changed-files@v1
      - name: Step 3 - Show changed files
        run: echo "${changed_file}."
