name: Docker

on:
  workflow_dispatch:

jobs:
  backup:
    name: Docker Container Update
    runs-on: ubuntu-latest

    env:
      ADMIN_TOKEN: ${{ secrets.ADMIN_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        env:
          ADMIN_TOKEN: ${{ secrets.ADMIN_TOKEN }}
          DUO_IKEY: ${{ secrets.DUO_IKEY }}
          DUO_SKEY: ${{ secrets.DUO_SKEY }}
          SMTP_FROM: ${{ secrets.SMTP_FROM }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
        with:
          host: ${{ secrets.RACKNERD_IP }}
          username: jackstockley
          key: ${{ secrets.RACKNERD_SSH_KEY }}
          envs: ADMIN_TOKEN,DUO_IKEY,DUO_SKEY,SMTP_FROM,SMTP_PASSWORD,CLOUDFLARE_API_TOKEN,CLOUDFLARE_ZONE_ID
          script: |
            cd /home/jackstockley/infrastructure/
            git fetch
            git reset --hard HEAD
            git merge '@{u}'
            git pull;
            bash docker/replace.sh
