name: Hassio Device Errors

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  backup:
    name: Hassio Device Errors
    runs-on: ubuntu-latest
    
    steps:
      - name: Step 1 - Checkout
        uses: actions/checkout@v4
      - name: Step 2 - Set Timezone
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "America/Chicago"
      - name: Step 3 - Setup and Connect to Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:github
      - name: Step 4 - Create config file
        run: |
          mkdir resources
          touch resources/config.toml
          echo "[Bitwarden]"  >> resources/config.toml
          echo "server = '${{ secrets.BITWARDEN_URL }}'"  >> resources/config.toml
          echo "username = '${{ secrets.BITWARDEN_USERNAME }}'"  >> resources/config.toml
          echo "password = '${{ secrets.BITWARDEN_PASSWORD }}'"  >> resources/config.toml
          echo "client_id = '${{ secrets.BITWARDEN_CLIENT_ID }}'" >> resources/config.toml
          echo "client_secret = '${{ secrets.BITWARDEN_CLIENT_SECRET }}'" >> resources/config.toml
          echo "[Hassio]"  >> resources/config.toml
          echo "[Hassio.Iowa-Home]"  >> resources/config.toml
          echo "url = '${{ secrets.IOWA_HOME_URL }}'"  >> resources/config.toml
          echo "credential_id = '${{ secrets.IOWA_HOME_CRED_ID }}'"  >> resources/config.toml
      - name: Step 5 - Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' 
      - name: Step 6 - Install Poetry and Dependencies
        run: |
          pipx install poetry==1.8
          poetry install --no-root --only main,hassio
          poetry run playwright install --with-deps chromium
      - name: Step 7 - Run Tests
        run: poetry run pytest tests/test_hassio.py
