---
name: Lint

on:
  pull_request:
    branches:
      - main
      - beta
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Checkout code
        uses: actions/checkout@v4.2.2

      - name: Step 2 - Setup Node.js environment
        uses: actions/setup-node@v4.1.0

      - name: Step 2 - Install Linters
        run: |
          sudo apt-get update
          sudo apt-get install -y yamllint shellcheck shfmt

      - name: Step 3 - Lint Yaml Files
        run: yamllint -s .

      - name: Step 4 - Lint Docker Compose Files
        run: npx dclint -r --max-warnings 0 docker/

      - name: Step 5 - Lint Shell Scripts
        run: |
          find . -type f \( -name '*.sh' -o -name '*.bash' -o -name '*.ksh' -o -name '*.bashrc' -o -name '*.bash_profile' -o -name '*.bash_login' -o -name '*.bash_logout' \) -print0 | xargs -0 shellcheck -x -S style
          shfmt -d -i 4 -ci .
