---
name: Multi-vpn

on:
  workflow_dispatch:

jobs:
  multi-wireguard:
    name: Multi-Wireguard
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Set Timezone
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "America/Chicago"

      - name: Step 2 - WireGuard Connection
        run: |
          sudo apt-get update
          sudo apt-get install -y wireguard resolvconf
          echo "${{ secrets.IOWA_HOME_VPN_CONF }}" > wg0.conf
          sudo chmod 600 wg0.conf
          sudo cp wg0.conf /etc/wireguard/
          sudo wg-quick up wg0

      - name: Step 3 - Ping Servers
        run: |
          ping -c 5 192.168.0.107
          ping -c 5 192.168.1.1
          ping -c 5 google.com
