name: Publish Poetry Docker image

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types:
      - closed
    paths:
      - docker/images/poetry/**
      - .github/workflows/poetry-deploy.yml
jobs:
  poetry_image_deploy:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.6.1

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to the Container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ACTIONS_GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: |
            jnstockley/poetry
            ghcr.io/jnstockley/poetry

      - name: Build Docker image
        id: build
        uses: docker/build-push-action@v6.8.0
        with:
          context: docker/images/poetry/.
          platforms: linux/amd64,linux/arm64
          push: true
          tags: jnstockley/poetry:latest
          labels: ${{ steps.meta.outputs.labels }}

      - name: Get Python version
        id: get-python-version
        run: |
          PYTHON_VERSION=$(docker run --rm jnstockley/poetry:latest python --version | awk '{print $2}')
          echo "PYTHON_VERSION=$PYTHON_VERSION" >> $GITHUB_ENV

      - name: Get Poetry version
        id: get-poetry-version
        run: |
          POETRY_VERSION=$(docker run --rm jnstockley/poetry:latest poetry --version | awk '{print $3}')
          echo "POETRY_VERSION=$POETRY_VERSION" >> $GITHUB_ENV

      - name: Build and push Docker images
        uses: docker/build-push-action@v6.8.0
        with:
          context: docker/images/poetry/.
          platforms: linux/amd64,linux/arm64
          push: true
          tags: jnstockley/poetry:${{ env.POETRY_VERSION }}-python${{ env.PYTHON_VERSION }}
          labels: ${{ steps.meta.outputs.labels }}

