name: Speedtest

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  backup:
    name: Speedtest
    #runs-on: self-hosted
    runs-on: ubuntu-latest

    steps:
      #- name: Step 1 - Checkout
      #  uses: actions/checkout@v4

      #- name: Step 2 - Setup and Connect to Tailscale
      #  uses: tailscale/github-action@v2
      #  with:
      #    oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
      #    oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
      #    tags: tag:github
      #- name: Step 1 - Install Speedtest CLI
      #  run: |
      #    curl -s https://packagecloud.io/install/repositories/ookla/speedtest-cli/script.deb.sh | sudo bash
      #    sudo apt install speedtest
      #    speedtest --accept-license
      #- name: Step 2 - Chicago Speedtest
      #  run: |
      #    echo ${{ secrets.RACKNER_USER_PASSWORD }} | sudo -S tailscale set --advertise-exit-node=false
      #    echo ${{ secrets.RACKNER_USER_PASSWORD }} | sudo -S tailscale set --exit-node chicago-home
      #    speedtest --server-id=1776 --format=json
      #    echo ${{ secrets.RACKNER_USER_PASSWORD }} | sudo -S tailscale set --exit-node ""
      #    echo ${{ secrets.RACKNER_USER_PASSWORD }} | sudo -S tailscale set --advertise-exit-node
      - name: Step 2 - Setup and Connect to Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:github
      - name: Step 3 - Iowa Speedtest
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 192.168.0.17
          port: 22
          username: root
          key: ${{ secrets.IOWA_HOME_SSH_KEY }}
          script: |
            mkdir -p /root/speedtest/
            cd /root/speedtest/
            wget https://install.speedtest.net/app/cli/ookla-speedtest-1.2.0-linux-aarch64.tgz
            tar -xvzf ookla-speedtest-1.2.0-linux-aarch64.tgz
            chmod +x speedtest
            ./speedtest --accept-license
            ./speedtest --server-id=10134 --format=json
            cd ..
            rm -rf /root/speedtest/

          #- name: Step 3 - Iowa Speedtest
      #  run: |
      #    echo ${{ secrets.RACKNER_USER_PASSWORD }} | sudo -S tailscale set --advertise-exit-node=false
      #    echo ${{ secrets.RACKNER_USER_PASSWORD }} | sudo -S tailscale set --exit-node iowa-home
      #    speedtest --server-id=10134 --format=json
      #    echo ${{ secrets.RACKNER_USER_PASSWORD }} | sudo -S tailscale set --exit-node ""
      #    echo ${{ secrets.RACKNER_USER_PASSWORD }} | sudo -S tailscale set --advertise-exit-node
          
      

      #- name: Step 5 - Chicago Speedtest
      #  run: |

      #           echo ${{ secrets.RACKNER_USER_PASSWORD }} | sudo -S tailscale set --advertise-exit-node=false
      # echo ${{ secrets.RACKNER_USER_PASSWORD }} | sudo -S tailscale up --exit-node=iowa-home --accept-routes --advertise-tags=tag:github --hostname=github-fv-az1208-982

      # echo ${{ secrets.RACKNER_USER_PASSWORD }} | sudo -S tailscale up --exit-node=chicago-home --accept-routes --advertise-tags=tag:github --hostname=github-fv-az1208-982 --reset
      # speedtest --server-id=1776 --format=json
      #    echo ${{ secrets.RACKNER_USER_PASSWORD }} | sudo -S tailscale up --exit-node=iowa-home --accept-routes --advertise-tags=tag:github --hostname=github-fv-az1208-982
      #    speedtest --accept-license
      #    speedtest --servers
      #    speedtest --server-id=10134 --format=json
      #    echo ${{ secrets.RACKNER_USER_PASSWORD }} | sudo -S tailscale down --accept-risk=all

#echo ${{ secrets.RACKNER_USER_PASSWORD }} | sudo -S tailscale set --exit-node iowa-home
#          speedtest --server-id=10134 --format=json