name: Speedtest

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  backup:
    name: Speedtest
    runs-on: self-hosted

    steps:
      #- name: Step 1 - Checkout
      #  uses: actions/checkout@v4

      #- name: Step 2 - Setup and Connect to Tailscale
      #  uses: tailscale/github-action@v2
      #  with:
      #    oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
      #    oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
      #    tags: tag:github
      - name: Step 3 - Install Speedtest CLI
        run: |
          curl -s https://packagecloud.io/install/repositories/ookla/speedtest-cli/script.deb.sh | echo ${{ secrets.RACKNER_USER_PASSWORD }} | sudo -S bash
          echo echo ${{ secrets.RACKNER_USER_PASSWORD }} | sudo -S apt install speedtest
      - name: Step 4 - Iowa Speedtest
        run: |
          echo ${{ secrets.RACKNER_USER_PASSWORD }} | sudo -S tailscale down --accept-risk=all
          echo ${{ secrets.RACKNER_USER_PASSWORD }} | sudo -S tailscale set --exit-node=iowa-home
          speedtest --accept-license
          speedtest --server-id=10134 --format=json
          echo ${{ secrets.RACKNER_USER_PASSWORD }} | sudo -S tailscale set --exit-node=chicago-home
          speedtest --accept-license
          speedtest --server-id=10134 --format=json
          echo ${{ secrets.RACKNER_USER_PASSWORD }} | sudo -S tailscale up with the --advertise-exit-node
      #- name: Step 5 - Chicago Speedtest
      #  run: |
      # echo ${{ secrets.RACKNER_USER_PASSWORD }} | sudo -S tailscale up --exit-node=iowa-home --accept-routes --advertise-tags=tag:github --hostname=github-fv-az1208-982

      # echo ${{ secrets.RACKNER_USER_PASSWORD }} | sudo -S tailscale up --exit-node=chicago-home --accept-routes --advertise-tags=tag:github --hostname=github-fv-az1208-982 --reset
      # speedtest --server-id=1776 --format=json
      #    echo ${{ secrets.RACKNER_USER_PASSWORD }} | sudo -S tailscale up --exit-node=iowa-home --accept-routes --advertise-tags=tag:github --hostname=github-fv-az1208-982
      #    speedtest --accept-license
      #    speedtest --servers
      #    speedtest --server-id=10134 --format=json
      #    echo ${{ secrets.RACKNER_USER_PASSWORD }} | sudo -S tailscale down --accept-risk=all
