name: Speedtest

on:
  #schedule:
  #  - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  backup:
    name: Speedtest
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Checkout
        uses: actions/checkout@v4

      - name: Step 2 - Setup and Connect to Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:github
      - name: Step 3 - Install Speedtest CLI
        run: |
          curl -s https://packagecloud.io/install/repositories/ookla/speedtest-cli/script.deb.sh | sudo bash
          sudo apt install speedtest
      - name: Step 4 - Iowa Speedtest
        run: |
          tailscale up --exit-node=chicago-home
          speedtest --list
          speedtest --server 47744 --secure --json
      - name: Step 5 - Chicago Speedtest
        run: |
          tailscale up --exit-node=iowa-home
          speedtest --list
          speedtest --server 10145 --secure --json
      
