name: SSH-Test

on:
  workflow_dispatch:

jobs:
  ssh-test:
    name: SSH Test
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Setup and Connect to Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:github

      - name: Step 2 - Ping Racknerd
        run:
          ping ${{ secrets.RACKNERD_IP }}

      - name: Step 3 - Deploy containers (Racknerd)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.RACKNERD_IP }}
          username: jackstockley
          key: ${{ secrets.RACKNERD_SSH_KEY }}
          passphrase: ${{ secrets.RACKNERD_SSH_PASSWORD }}
          script: |
            echo "Connected to Racknerd"

      - name: Step 2 - Ping Photo Server
        run:
          ping ${{ secrets.PHOTO_SERVER_IP }}

      - name: Step 3 - Deploy containers (Photo Server)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PHOTO_SERVER_IP }}
          username: jackstockley
          key: ${{ secrets.PHOTO_SERVER_SSH_KEY }}
          passphrase: ${{ secrets.PHOTO_SERVER_SSH_PASSWORD }}
          script: |
            echo "Connected to Photo Server"
