---
name: Remote OpenTofu State
on:
  push:
    branches:
      - main
      # paths:
      #   - 'tf/**'
  pull_request:
    branches:
      - main
      - beta
      # paths:
      #   - 'tf/**'

jobs:
  lint:
    name: Lint Open Tofu code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up OpenTofu
        uses: opentofu/setup-opentofu@v2
        with:
          tofu_version_file: tf/.opentofu-version

      - name: Check format
        run: tofu fmt -recursive -check
  changes:
    name: Detect changed paths
    runs-on: ubuntu-latest
    outputs:
      adguard: ${{ steps.filter.outputs.adguard }}
      authentik: ${{ steps.filter.outputs.authentik }}
      cloudflare: ${{ steps.filter.outputs.cloudflare }}
      gitea: ${{ steps.filter.outputs.gitea }}
      infisical: ${{ steps.filter.outputs.infisical }}
      proxmox: ${{ steps.filter.outputs.proxmox }}
      unifi: ${{ steps.filter.outputs.unifi }}
      uptime-kuma: ${{ steps.filter.outputs.uptime-kuma }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Filter changed paths
        uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            adguard:
              - 'tf/adguard/**'
            authentik:
              - 'tf/authentik/**'
            cloudflare:
              - 'tf/cloudflare/**'
            gitea:
              - 'tf/gitea/**'
            infisical:
              - 'tf/infisical/**'
            proxmox:
              - 'tf/proxmox/**'
            unifi:
              - 'tf/unifi/**'
            uptime-kuma:
              - 'tf/uptime-kuma/**'

  adguard:
    name: Run AdGuard
    runs-on: ubuntu-latest
    needs: [lint, changes]
    if: needs.changes.outputs.adguard == 'true'
    environment: adguard
    permissions:  # Needed for Infisical
      id-token: write  # Required for OIDC authentication
      contents: read   # Required for checking out code
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up OpenTofu
        uses: opentofu/setup-opentofu@v2
        with:
          tofu_version_file: tf/.opentofu-version

      - name: Fetch secrets from Infisical
        uses: Infisical/secrets-action@v1.0.16
        with:
          method: "oidc"
          identity-id: "646b2754-c197-462a-a2c3-9db2507b4b8e"
          domain: "https://secrets.jstockley.com"
          project-slug: "open-tofu"
          env-slug: "adguard"

      - name: Init AdGuard
        run: |
          cd tf/adguard
          tofu init \
          -backend-config=address=${{env.TF_ADDRESS}} \
          -backend-config=lock_address=${{env.TF_ADDRESS}}/lock \
          -backend-config=unlock_address=${{env.TF_ADDRESS}}/lock \
          -backend-config=username=${{env.TF_USERNAME}} \
          -backend-config=password=${{env.TF_PASSWORD}} \
          -backend-config=lock_method=POST \
          -backend-config=unlock_method=DELETE \
          -backend-config=retry_wait_min=5 \
          -reconfigure \
          -upgrade

      - name: Validate AdGuard
        run: |
          cd tf/adguard
          tofu validate

      - name: Plan and Apply AdGuard
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          TF_VAR_adguard_username: ${{ env.ADGUARD_USERNAME }}
          TF_VAR_adguard_password: ${{ env.ADGUARD_PASSWORD }}
          TF_VAR_gitlab_username: ${{ env.TF_USERNAME }}
          TF_VAR_gitlab_access_token: ${{ env.TF_PASSWORD }}
        run: |
          cd tf/adguard
          tofu plan -out=tfplan
          tofu apply -auto-approve tfplan

  authentik:
    name: Run Authentik
    runs-on: ubuntu-latest
    needs: [lint, changes]
    if: needs.changes.outputs.authentik == 'true'
    environment: authentik
    permissions:  # Needed for Infisical
      id-token: write  # Required for OIDC authentication
      contents: read   # Required for checking out code
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up OpenTofu
        uses: opentofu/setup-opentofu@v2
        with:
          tofu_version_file: tf/.opentofu-version

      - name: Fetch secrets from Infisical
        uses: Infisical/secrets-action@v1.0.16
        with:
          method: "oidc"
          identity-id: "646b2754-c197-462a-a2c3-9db2507b4b8e"
          domain: "https://secrets.jstockley.com"
          project-slug: "open-tofu"
          env-slug: "authentik"

      - name: Init Authentik
        run: |
          cd tf/authentik
          tofu init \
          -backend-config=address=${{env.TF_ADDRESS}} \
          -backend-config=lock_address=${{env.TF_ADDRESS}}/lock \
          -backend-config=unlock_address=${{env.TF_ADDRESS}}/lock \
          -backend-config=username=${{env.TF_USERNAME}} \
          -backend-config=password=${{env.TF_PASSWORD}} \
          -backend-config=lock_method=POST \
          -backend-config=unlock_method=DELETE \
          -backend-config=retry_wait_min=5 \
          -reconfigure \
          -upgrade

      - name: Validate Authentik
        run: |
          cd tf/authentik
          tofu validate

      - name: Plan and Apply Authentik
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          TF_VAR_authentik_api_token: ${{ env.AUTHENTIK_API_TOKEN }}
          TF_VAR_gitlab_username: ${{ env.TF_USERNAME }}
          TF_VAR_gitlab_access_token: ${{ env.TF_PASSWORD }}
        run: |
          cd tf/authentik
          tofu plan -out=tfplan
          tofu apply -auto-approve tfplan

  cloudflare:
    name: Run cloudflare
    runs-on: ubuntu-latest
    needs: [lint, changes]
    if: needs.changes.outputs.cloudflare == 'true'
    environment: cloudflare
    permissions:  # Needed for Infisical
      id-token: write  # Required for OIDC authentication
      contents: read   # Required for checking out code
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up OpenTofu
        uses: opentofu/setup-opentofu@v2
        with:
          tofu_version_file: tf/.opentofu-version

      - name: Fetch secrets from Infisical
        uses: Infisical/secrets-action@v1.0.16
        with:
          method: "oidc"
          identity-id: "646b2754-c197-462a-a2c3-9db2507b4b8e"
          domain: "https://secrets.jstockley.com"
          project-slug: "open-tofu"
          env-slug: "cloudflare"

      - name: Init Cloudflare
        run: |
          cd tf/cloudflare
          tofu init \
          -backend-config=address=${{env.TF_ADDRESS}} \
          -backend-config=lock_address=${{env.TF_ADDRESS}}/lock \
          -backend-config=unlock_address=${{env.TF_ADDRESS}}/lock \
          -backend-config=username=${{env.TF_USERNAME}} \
          -backend-config=password=${{env.TF_PASSWORD}} \
          -backend-config=lock_method=POST \
          -backend-config=unlock_method=DELETE \
          -backend-config=retry_wait_min=5 \
          -reconfigure \
          -upgrade

      - name: Validate Cloudflare
        run: |
          cd tf/cloudflare
          tofu validate

      - name: Plan and Apply Cloudflare
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          TF_VAR_cloudflare_api_token: ${{ env.CLOUDFLARE_API_TOKEN }}
          TF_VAR_cloudflare_zone_id: ${{ env.CLOUDFLARE_ZONE_ID }}
          TF_VAR_cloudflare_account_id: ${{ env.CLOUDFLARE_ACCOUNT_ID }}
          TF_VAR_cloudflare_authentik_client_id: ${{ env.CLOUDFLARE_AUTHENTIK_CLIENT_ID }}
          TF_VAR_jstockley_api_key: ${{ env.JSTOCKLEY_API_KEY }}
          TF_VAR_gitlab_username: ${{ env.TF_USERNAME }}
          TF_VAR_gitlab_access_token: ${{ env.TF_PASSWORD }}
        run: |
          cd tf/cloudflare
          tofu plan -out=tfplan
          tofu apply -auto-approve tfplan

  gitea:
    name: Run gitea
    runs-on: ubuntu-latest
    needs: [lint, changes]
    # if: needs.changes.outputs.gitea == 'true'
    environment: gitea
    permissions:  # Needed for Infisical
      id-token: write  # Required for OIDC authentication
      contents: read   # Required for checking out code
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up OpenTofu
        uses: opentofu/setup-opentofu@v2
        with:
          tofu_version_file: tf/.opentofu-version

      - name: Fetch secrets from Infisical
        uses: Infisical/secrets-action@v1.0.16
        with:
          method: "oidc"
          identity-id: "646b2754-c197-462a-a2c3-9db2507b4b8e"
          domain: "https://secrets.jstockley.com"
          project-slug: "open-tofu"
          env-slug: "gitea"

      - name: Init Gitea
        run: |
          cd tf/gitea
          tofu init \
          -backend-config=address=${{env.TF_ADDRESS}} \
          -backend-config=lock_address=${{env.TF_ADDRESS}}/lock \
          -backend-config=unlock_address=${{env.TF_ADDRESS}}/lock \
          -backend-config=username=${{env.TF_USERNAME}} \
          -backend-config=password=${{env.TF_PASSWORD}} \
          -backend-config=lock_method=POST \
          -backend-config=unlock_method=DELETE \
          -backend-config=retry_wait_min=5 \
          -reconfigure \
          -upgrade

      - name: Validate gitea
        run: |
          cd tf/gitea
          tofu validate

      - name: Plan and Apply gitea
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          TF_VAR_gitea_token: ${{ env.GITEA_TOKEN }}
          TF_VAR_gitea_password: ${{ env.GITEA_PASSWORD }}
          TF_VAR_github_token: ${{ env.GITHUB_TOKEN }}
          TF_VAR_research_git_token: ${{ env.RESEARCH_GIT_TOKEN }}
          TF_VAR_gitlab_username: ${{ env.TF_USERNAME }}
          TF_VAR_gitlab_access_token: ${{ env.TF_PASSWORD }}
        run: |
          cd tf/gitea
          tofu plan -out=tfplan
          tofu apply -auto-approve tfplan
