---
name: Remote OpenTofu State
on:
  workflow_dispatch:

jobs:
  lint:
    name: Lint Open Tofu code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up OpenTofu
        uses: opentofu/setup-opentofu@v2
        with:
          tofu_version_file: tf/.opentofu-version

      - name: Check format
        run: tofu fmt -recursive -check

  adguard:
    name: Run AdGuard
    runs-on: ubuntu-latest
    needs: lint
    environment: adguard
    permissions: # Needed for Infisical
      id-token: write  # Required for OIDC authentication
      contents: read   # Required for checking out code
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up OpenTofu
        uses: opentofu/setup-opentofu@v2
        with:
          tofu_version_file: tf/.opentofu-version

      - name: Fetch secrets from Infisical
        uses: Infisical/secrets-action@v1.0.16
        with:
          method: "oidc"
          identity-id: "646b2754-c197-462a-a2c3-9db2507b4b8e"
          domain: "https://secrets.jstockley.com"
          project-slug: "open-tofu"
          env-slug: "adguard"

      - name: Init AdGuard
        run: |
          cd tf/adguard
          tofu init \
          -backend-config=address=${{env.TF_ADDRESS}} \
          -backend-config=lock_address=${{env.TF_ADDRESS}}/lock \
          -backend-config=unlock_address=${{env.TF_ADDRESS}}/lock \
          -backend-config=username=${{env.TF_USERNAME}} \
          -backend-config=password=${{env.TF_PASSWORD}} \
          -backend-config=lock_method=POST \
          -backend-config=unlock_method=DELETE \
          -backend-config=retry_wait_min=5 \
          -reconfigure \
          -upgrade

      - name: Validate AdGuard
        run: |
          cd tf/adguard
          tofu validate

      - name: Plan and Apply AdGuard
        env:
          TF_VAR_adguard_username: ${{ env.ADGUARD_USERNAME }}
          TF_VAR_adguard_password: ${{ env.ADGUARD_PASSWORD }}
          TF_VAR_gitlab_username: ${{ env.TF_USERNAME }}
          TF_VAR_gitlab_access_token: ${{ env.TF_PASSWORD }}
        run: |
          cd tf/adguard
          tofu plan -out=tfplan
          tofu apply -auto-approve tfplan
