name: WireGuard test

on:
  workflow_dispatch:

jobs:
  wireguard_example:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt update
          sudo apt install -y wireguard
          echo "${{ secrets.IOWA_HOME_PRIV_KEY }}" > privatekey
          sudo ip link add dev wg0 type wireguard
          sudo ip address add dev wg0 10.13.13.1 peer 10.13.13.5
          sudo wg set wg0 listen-port 51820 private-key privatekey peer lcB3rrkkH0ndE8+js0JYjlf3A/7AMdcuK4hbnycW+Rw= allowed-ips 0.0.0.0/0 endpoint iowa.vpn.jstockley.com:51820
          sudo ip link set up dev wg0

      - run: |
          curl -4 icanhazip.com
          curl -vvv http://192.168.0.1
